//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegasoftDelayedPostingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtReportAutomation
    {
        public string Report { get; set; }
        public string ServiceScheduleMode { get; set; }
        public Nullable<System.TimeSpan> ServiceRunTime { get; set; }
        public string ServiceWeeklyDay { get; set; }
        public Nullable<int> ServiceMonthlyDate { get; set; }
        public string ServiceActive { get; set; }
        public Nullable<System.DateTime> LastRunDate { get; set; }
        public Nullable<int> ServiceIntervalMin { get; set; }
        public string ToEmail { get; set; }
        public string ReportPath { get; set; }
        public string Title { get; set; }
    }
}
