//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegasoftDelayedPostingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtSystemSetting
    {
        public int Id { get; set; }
        public Nullable<bool> UseRoles { get; set; }
        public string SmtpHost { get; set; }
        public Nullable<int> SmtpPort { get; set; }
        public string FromAddress { get; set; }
        public string ReportExportPath { get; set; }
        public Nullable<int> ScadaServiceIntervalMin { get; set; }
        public Nullable<decimal> MegasoftServiceIntervalMin { get; set; }
        public bool Dashboard { get; set; }
        public bool BranchAccess { get; set; }
        public bool GlAuthorisation { get; set; }
        public bool ProductClassLimit { get; set; }
        public bool SmartScan { get; set; }
        public bool ScaleAccess { get; set; }
        public bool WarehouseAccess { get; set; }
        public bool PrinterAccess { get; set; }
        public bool DepartmentAccess { get; set; }
        public bool ReportAccess { get; set; }
        public string FromAddressPassword { get; set; }
    }
}
