//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmFormControl
    {
        public string FormType { get; set; }
        public decimal SequenceNumber { get; set; }
        public string FieldName { get; set; }
        public string FieldDescription { get; set; }
        public string FieldType { get; set; }
        public decimal FieldLength { get; set; }
        public decimal FieldDecimals { get; set; }
        public string DefaultValue { get; set; }
        public decimal AllowNull { get; set; }
        public string TableName { get; set; }
        public decimal FormNumber { get; set; }
        public string ColumnName { get; set; }
        public string IndexFlag { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
