//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmFormData
    {
        public string FormType { get; set; }
        public string KeyField { get; set; }
        public string FieldName { get; set; }
        public string AlphaValue { get; set; }
        public decimal NumericValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
