//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmFormList
    {
        public AdmFormList()
        {
            this.AdmFormDatas = new HashSet<AdmFormData>();
            this.AdmFormControls = new HashSet<AdmFormControl>();
            this.AdmFormValidations = new HashSet<AdmFormValidation>();
        }
    
        public string FormType { get; set; }
        public string FieldName { get; set; }
        public string FieldList { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<AdmFormData> AdmFormDatas { get; set; }
        public virtual ICollection<AdmFormControl> AdmFormControls { get; set; }
        public virtual ICollection<AdmFormValidation> AdmFormValidations { get; set; }
    }
}
