//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmMultimedia
    {
        public string MultimediaFlag { get; set; }
        public string KeyField { get; set; }
        public string ObjectType { get; set; }
        public string ObjectText { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
