//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adr_DBLog_Analogs
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public string Tagname { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> Quality { get; set; }
    }
}
