//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApBranch
    {
        public ApBranch()
        {
            this.ApSuppliers = new HashSet<ApSupplier>();
        }
    
        public string Branch { get; set; }
        public string Description { get; set; }
        public string ApBrnGlCode { get; set; }
        public string ApBrnDscGlCode { get; set; }
        public string PoPrefix { get; set; }
        public decimal PoNextNumber { get; set; }
        public string GrnPrefix { get; set; }
        public decimal GrnNextNumber { get; set; }
        public string Nationality { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<ApSupplier> ApSuppliers { get; set; }
    }
}
