//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApSupplier_
    {
        public string Supplier { get; set; }
        public string Name { get; set; }
        public string BenificiaryBankNam { get; set; }
        public string ValueAddingSupplie { get; set; }
        public Nullable<decimal> BlackOwnership { get; set; }
        public Nullable<decimal> BlackWomenOwnershi { get; set; }
        public string EmpoweringSupplier { get; set; }
        public string BeeLevel { get; set; }
        public string EnterpriseType { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ApType { get; set; }
        public string PriceMethod { get; set; }
        public string SupplierGroup { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
