//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApSupplier
    {
        public ApSupplier()
        {
            this.GrnDetails = new HashSet<GrnDetail>();
            this.InvMasters = new HashSet<InvMaster>();
            this.InvWarehouses = new HashSet<InvWarehouse>();
            this.PorMasterHdrs = new HashSet<PorMasterHdr>();
            this.PorSupStkInfoes = new HashSet<PorSupStkInfo>();
        }
    
        public string Supplier { get; set; }
        public string SupplierName { get; set; }
        public string SupShortName { get; set; }
        public string SupplierType { get; set; }
        public string SupplierClass { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Contact { get; set; }
        public string Area { get; set; }
        public string Email { get; set; }
        public string FaxContact { get; set; }
        public string UserField1 { get; set; }
        public string UserField2 { get; set; }
        public string Currency { get; set; }
        public decimal CurrentBalance { get; set; }
        public decimal PyrEndBalance { get; set; }
        public Nullable<System.DateTime> LastPurchDate { get; set; }
        public Nullable<System.DateTime> FirstPurchDate { get; set; }
        public string LineDiscCode { get; set; }
        public string InvDiscCode { get; set; }
        public string TermsCode { get; set; }
        public string LastChequePrint { get; set; }
        public string ReservedForUsa { get; set; }
        public decimal DefaultChequeDay { get; set; }
        public decimal YtdAmount1099 { get; set; }
        public string Required1099 { get; set; }
        public string GrnMatchReqd { get; set; }
        public string LctRequired { get; set; }
        public string EdiTypeFlag { get; set; }
        public string EdiReceiverCode { get; set; }
        public string WithTaxId { get; set; }
        public string WithTaxCode { get; set; }
        public decimal Pyr1099Val { get; set; }
        public string MerchGlCode { get; set; }
        public string FreightGlCode { get; set; }
        public decimal NumMthsBeforDel { get; set; }
        public decimal NumMonthsZero { get; set; }
        public decimal PurchValMth1 { get; set; }
        public decimal PurchValMth2 { get; set; }
        public decimal PurchValMth3 { get; set; }
        public decimal PurchValMth4 { get; set; }
        public decimal PurchValMth5 { get; set; }
        public decimal PurchValMth6 { get; set; }
        public decimal PurchValMth7 { get; set; }
        public decimal PurchValMth8 { get; set; }
        public decimal PurchValMth9 { get; set; }
        public decimal PurchValMth10 { get; set; }
        public decimal PurchValMth11 { get; set; }
        public decimal PurchValMth12 { get; set; }
        public decimal MtdTaxVal { get; set; }
        public decimal YtdTaxVal { get; set; }
        public string PurchOrdAllowed { get; set; }
        public decimal MinPoVal { get; set; }
        public decimal MinPoMass { get; set; }
        public decimal MinPoVolume { get; set; }
        public string Nationality { get; set; }
        public string TaxRegnNum { get; set; }
        public string EdiFax { get; set; }
        public string BankAccount { get; set; }
        public string BankBranch { get; set; }
        public string FaxRemitFlag { get; set; }
        public string FaxRemitNum { get; set; }
        public string PayeRef1099 { get; set; }
        public decimal MtdTax2Val { get; set; }
        public decimal YtdTax2Val { get; set; }
        public decimal MtdMerchVal { get; set; }
        public decimal MtdFreightVal { get; set; }
        public decimal MtdOtherVal { get; set; }
        public decimal MtdDsbVal { get; set; }
        public decimal YtdMerchVal { get; set; }
        public decimal YtdFreightVal { get; set; }
        public decimal YtdOtherVal { get; set; }
        public decimal YtdDsbVal { get; set; }
        public decimal PyrMerchVal { get; set; }
        public decimal PyrFreightVal { get; set; }
        public decimal PyrOtherVal { get; set; }
        public decimal PyrDsbVal { get; set; }
        public Nullable<System.DateTime> LastChequeDate { get; set; }
        public string LastChequeBank { get; set; }
        public decimal LastCheque { get; set; }
        public decimal LastChequeVal { get; set; }
        public string ChLanguage { get; set; }
        public string SupplierChName { get; set; }
        public Nullable<System.DateTime> DateSuppAdded { get; set; }
        public decimal DefaultFmt1099 { get; set; }
        public decimal MinPay1099 { get; set; }
        public string PoDefaultDoc { get; set; }
        public string OnHold { get; set; }
        public string AskYtdValue1099 { get; set; }
        public string Contracts { get; set; }
        public string PayByEft { get; set; }
        public string EftBankAccType { get; set; }
        public string DefTaxCode { get; set; }
        public string DeliveryTerms { get; set; }
        public decimal TransactionNature { get; set; }
        public string RemitEmail { get; set; }
        public string AutoVoucherReqd { get; set; }
        public string LanguageCode { get; set; }
        public string FaxVoucherFlag { get; set; }
        public string FaxVoucherNum { get; set; }
        public string VoucherEmail { get; set; }
        public string OutOfState { get; set; }
        public string CollectTax { get; set; }
        public string State { get; set; }
        public string CountyZip { get; set; }
        public string City { get; set; }
        public string ShippingLocation { get; set; }
        public byte[] TimeStamp { get; set; }
        public decimal MtdTaxReliefVal { get; set; }
        public decimal YtdTaxReliefVal { get; set; }
        public string WithTaxSupplierInd { get; set; }
        public string WithTaxExpenseType { get; set; }
        public string FaxPoFlag { get; set; }
        public string PoEmail { get; set; }
        public string DefRevChgTaxCode { get; set; }
        public string PrimarySupplier { get; set; }
    
        public virtual ICollection<GrnDetail> GrnDetails { get; set; }
        public virtual ICollection<InvMaster> InvMasters { get; set; }
        public virtual ICollection<InvWarehouse> InvWarehouses { get; set; }
        public virtual ICollection<PorMasterHdr> PorMasterHdrs { get; set; }
        public virtual ICollection<PorSupStkInfo> PorSupStkInfoes { get; set; }
    }
}
