//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomOperation
    {
        public string StockCode { get; set; }
        public string Version { get; set; }
        public string Release { get; set; }
        public string Route { get; set; }
        public decimal Operation { get; set; }
        public string WorkCentre { get; set; }
        public decimal WcRateInd { get; set; }
        public decimal WhatIfWcInd { get; set; }
        public string SubcontractFlag { get; set; }
        public decimal ISetUpTime { get; set; }
        public decimal IRunTime { get; set; }
        public decimal IStartupTime { get; set; }
        public decimal ITeardownTime { get; set; }
        public decimal IWaitTime { get; set; }
        public decimal IStartupQty { get; set; }
        public string IMachine { get; set; }
        public decimal IUnitCapacity { get; set; }
        public decimal IMaxWorkOpertrs { get; set; }
        public decimal IMaxProdUnits { get; set; }
        public decimal ITimeTaken { get; set; }
        public decimal IQuantity { get; set; }
        public decimal IRunTimeEnt { get; set; }
        public decimal ITimeTakenEnt { get; set; }
        public decimal IStartupQtyEnt { get; set; }
        public decimal IQuantityEnt { get; set; }
        public string SubSupplier { get; set; }
        public string SubPoStockCode { get; set; }
        public decimal SubQtyPer { get; set; }
        public string SubOrderUom { get; set; }
        public decimal SubOpUnitValue { get; set; }
        public decimal SubWhatIfValue { get; set; }
        public string SubPlanner { get; set; }
        public string SubBuyer { get; set; }
        public decimal SubLeadTime { get; set; }
        public decimal SubDockToStock { get; set; }
        public decimal SubOffsiteDays { get; set; }
        public string Milestone { get; set; }
        public decimal ElapsedTime { get; set; }
        public decimal MovementTime { get; set; }
        public string NarrationCode { get; set; }
        public decimal AutoNarrCode { get; set; }
        public decimal NumOfPieces { get; set; }
        public string InspectionFlag { get; set; }
        public decimal OperYieldPct { get; set; }
        public decimal OperYieldQty { get; set; }
        public decimal MinorSetup { get; set; }
        public string MinorSetupCode { get; set; }
        public string ToolSet { get; set; }
        public decimal ToolSetQty { get; set; }
        public decimal ToolConsumption { get; set; }
        public string TimeCalcFlag { get; set; }
        public string TransferQtyOrPct { get; set; }
        public decimal TransferQtyPct { get; set; }
        public string CoProductCostVal { get; set; }
        public string ResourceMask { get; set; }
        public decimal MaxOpDelay { get; set; }
        public decimal OperYieldQtyEnt { get; set; }
        public decimal TransferQtyPctEnt { get; set; }
        public decimal MaxOpSpan { get; set; }
        public decimal OpSlack { get; set; }
        public string AllowOpSplit { get; set; }
        public byte[] TimeStamp { get; set; }
        public string ProductCode { get; set; }
        public string LibraryCode { get; set; }
        public decimal FirstSeq { get; set; }
        public decimal SecondSeq { get; set; }
    
        public virtual BomRoute BomRoute { get; set; }
        public virtual BomWorkCentre BomWorkCentre { get; set; }
        public virtual InvMaster InvMaster { get; set; }
    }
}
