//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomRoute
    {
        public BomRoute()
        {
            this.WipMasters = new HashSet<WipMaster>();
            this.InvWhControls = new HashSet<InvWhControl>();
            this.BomOperations = new HashSet<BomOperation>();
            this.BomStructures = new HashSet<BomStructure>();
        }
    
        public string Route { get; set; }
        public string Description { get; set; }
        public string EccControlled { get; set; }
        public string JobsAllowed { get; set; }
        public byte[] TimeStamp { get; set; }
        public string WipBranch { get; set; }
    
        public virtual ICollection<WipMaster> WipMasters { get; set; }
        public virtual ICollection<InvWhControl> InvWhControls { get; set; }
        public virtual ICollection<BomOperation> BomOperations { get; set; }
        public virtual ICollection<BomStructure> BomStructures { get; set; }
    }
}
