//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomStructure
    {
        public string ParentPart { get; set; }
        public string Version { get; set; }
        public string Release { get; set; }
        public string Route { get; set; }
        public string SequenceNum { get; set; }
        public string Component { get; set; }
        public string ComVersion { get; set; }
        public string ComRelease { get; set; }
        public string EccConsumption { get; set; }
        public Nullable<System.DateTime> StructureOnDate { get; set; }
        public Nullable<System.DateTime> StructureOffDate { get; set; }
        public string OpOffsetFlag { get; set; }
        public decimal OperationOffset { get; set; }
        public decimal QtyPer { get; set; }
        public decimal ScrapPercentage { get; set; }
        public decimal ScrapQuantity { get; set; }
        public string SoOptionFlag { get; set; }
        public string SoPrintFlag { get; set; }
        public string InclScrapFlag { get; set; }
        public string ReasonForChange { get; set; }
        public string RefDesignator { get; set; }
        public string AssemblyPlace { get; set; }
        public string ItemNumber { get; set; }
        public decimal AutoNarrCode { get; set; }
        public string ComponentType { get; set; }
        public string InclKitIssues { get; set; }
        public string CreateSubJob { get; set; }
        public decimal WetWeightPercent { get; set; }
        public string IncludeBatch { get; set; }
        public string IncludeFromJob { get; set; }
        public string IncludeToJob { get; set; }
        public string FixedQtyPerFlag { get; set; }
        public decimal FixedQtyPer { get; set; }
        public string RollUpCost { get; set; }
        public string Warehouse { get; set; }
        public string IgnoreFloorFlag { get; set; }
        public string CoProductCostVal { get; set; }
        public string UomFlag { get; set; }
        public decimal QtyPerEnt { get; set; }
        public decimal ScrapQuantityEnt { get; set; }
        public decimal FixedQtyPerEnt { get; set; }
        public byte[] TimeStamp { get; set; }
        public string ProductCode { get; set; }
        public string LibraryCode { get; set; }
        public decimal FirstSeq { get; set; }
        public decimal SecondSeq { get; set; }
        public string OvrEccSpecIss { get; set; }
    
        public virtual BomRoute BomRoute { get; set; }
        public virtual InvWhControl InvWhControl { get; set; }
    }
}
