//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CusGenMaster_
    {
        public string GlCode { get; set; }
        public string ProductCategory { get; set; }
        public string QlikReportLine { get; set; }
        public string QlikReportHeader { get; set; }
        public byte[] TimeStamp { get; set; }
        public string PurchasingTaxCode { get; set; }
        public string PurchasingCategory { get; set; }
    }
}
