//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenControl
    {
        public string Company { get; set; }
        public decimal CurBalAsset { get; set; }
        public decimal CurBalLiability { get; set; }
        public decimal CurBalCapital { get; set; }
        public decimal CurBalRevenue { get; set; }
        public decimal CurBalExpense { get; set; }
        public decimal GlYear { get; set; }
        public decimal GlPeriod { get; set; }
        public decimal CurYrNxtJnl { get; set; }
        public decimal PrvYrNxtJnl { get; set; }
        public decimal NxtYrNxtJnl { get; set; }
        public decimal CurYrNxtEntGrp { get; set; }
        public decimal PrvYrNxtEntGrp { get; set; }
        public decimal NxtYrNxtEntGrp { get; set; }
        public string ShuffleFlag { get; set; }
        public string ProvEntryFlag { get; set; }
        public decimal OldestYearDet { get; set; }
        public decimal UnpYear { get; set; }
        public decimal UnpPer { get; set; }
        public decimal UnpJnl { get; set; }
        public string CurYrPrdStat1 { get; set; }
        public string CurYrPrdStat2 { get; set; }
        public string CurYrPrdStat3 { get; set; }
        public string CurYrPrdStat4 { get; set; }
        public string CurYrPrdStat5 { get; set; }
        public string CurYrPrdStat6 { get; set; }
        public string CurYrPrdStat7 { get; set; }
        public string CurYrPrdStat8 { get; set; }
        public string CurYrPrdStat9 { get; set; }
        public string CurYrPrdStat10 { get; set; }
        public string CurYrPrdStat11 { get; set; }
        public string CurYrPrdStat12 { get; set; }
        public string CurYrPrdStat13 { get; set; }
        public string CurYrPrdStat14 { get; set; }
        public string CurYrPrdStat15 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd1 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd2 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd3 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd4 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd5 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd6 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd7 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd8 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd9 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd10 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd11 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd12 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd13 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd14 { get; set; }
        public Nullable<System.DateTime> CurYrPrdEnd15 { get; set; }
        public string PrvYrPrdStat1 { get; set; }
        public string PrvYrPrdStat2 { get; set; }
        public string PrvYrPrdStat3 { get; set; }
        public string PrvYrPrdStat4 { get; set; }
        public string PrvYrPrdStat5 { get; set; }
        public string PrvYrPrdStat6 { get; set; }
        public string PrvYrPrdStat7 { get; set; }
        public string PrvYrPrdStat8 { get; set; }
        public string PrvYrPrdStat9 { get; set; }
        public string PrvYrPrdStat10 { get; set; }
        public string PrvYrPrdStat11 { get; set; }
        public string PrvYrPrdStat12 { get; set; }
        public string PrvYrPrdStat13 { get; set; }
        public string PrvYrPrdStat14 { get; set; }
        public string PrvYrPrdStat15 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd1 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd2 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd3 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd4 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd5 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd6 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd7 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd8 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd9 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd10 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd11 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd12 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd13 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd14 { get; set; }
        public Nullable<System.DateTime> PrvYrPrdEnd15 { get; set; }
        public decimal PctSpread1 { get; set; }
        public decimal PctSpread2 { get; set; }
        public decimal PctSpread3 { get; set; }
        public decimal PctSpread4 { get; set; }
        public decimal PctSpread5 { get; set; }
        public decimal PctSpread6 { get; set; }
        public decimal PctSpread7 { get; set; }
        public decimal PctSpread8 { get; set; }
        public decimal PctSpread9 { get; set; }
        public decimal PctSpread10 { get; set; }
        public decimal PctSpread11 { get; set; }
        public decimal PctSpread12 { get; set; }
        public decimal PctSpread13 { get; set; }
        public decimal PctSpread14 { get; set; }
        public decimal PctSpread15 { get; set; }
        public decimal NxtYr1NxtJnl { get; set; }
        public decimal NxtYr1NxtEntGrp { get; set; }
        public string AuthoriseJournals { get; set; }
        public string LimitCapturerView { get; set; }
        public string NextJnlNoPeriod { get; set; }
        public string AnalyzeAssets { get; set; }
        public string AnalyzeLiabilities { get; set; }
        public string AnalyzeCapital { get; set; }
        public string AnalyzeRevenue { get; set; }
        public string AnalyzeExpense { get; set; }
        public string AnalyzeStat { get; set; }
        public decimal NextAnalysisEntry { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
