//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrnDetail
    {
        public string Supplier { get; set; }
        public string Grn { get; set; }
        public string GrnSource { get; set; }
        public decimal Journal { get; set; }
        public decimal JournalEntry { get; set; }
        public Nullable<System.DateTime> OrigReceiptDate { get; set; }
        public string DebitRecGlCode { get; set; }
        public decimal GrnYear { get; set; }
        public decimal GrnMonth { get; set; }
        public string PurchaseOrder { get; set; }
        public decimal PurchaseOrderLin { get; set; }
        public string StockCode { get; set; }
        public string StockDescription { get; set; }
        public string SupCatalogueNum { get; set; }
        public string Warehouse { get; set; }
        public decimal QtyReceived { get; set; }
        public string QtyUom { get; set; }
        public decimal Decimals { get; set; }
        public string Job { get; set; }
        public decimal SubcontractOp { get; set; }
        public string DeliveryNote { get; set; }
        public string SourceCode { get; set; }
        public decimal OrigGrnValue { get; set; }
        public decimal CurGrnValue { get; set; }
        public decimal MatchedValue { get; set; }
        public decimal StdGrnValue { get; set; }
        public string PriceVarPrinted { get; set; }
        public string AuditTrailPrintd { get; set; }
        public string GrnMatchedFlag { get; set; }
        public string ProductClass { get; set; }
        public decimal GrnMatchedYear { get; set; }
        public decimal GrnMatchedMonth { get; set; }
        public decimal OrigPurchValue { get; set; }
        public string CostMultFlag { get; set; }
        public decimal CurrencyValue { get; set; }
        public string PostCurrency { get; set; }
        public decimal ConvRate { get; set; }
        public string MulDiv { get; set; }
        public string AccountCur { get; set; }
        public decimal AccConvRate { get; set; }
        public string AccMulDiv { get; set; }
        public string TriangCurrency { get; set; }
        public decimal TriangRate { get; set; }
        public string TriangMulDiv { get; set; }
        public string MTaxCode { get; set; }
        public byte[] TimeStamp { get; set; }
        public string WithTaxExpenseType { get; set; }
        public string TariffCode { get; set; }
    
        public virtual InvWarehouse InvWarehouse { get; set; }
        public virtual PorMasterHdr PorMasterHdr { get; set; }
        public virtual WipMaster WipMaster { get; set; }
        public virtual InvMaster InvMaster { get; set; }
        public virtual AdmTax AdmTax { get; set; }
        public virtual SalProductClassDe SalProductClassDe { get; set; }
        public virtual InvWhControl InvWhControl { get; set; }
        public virtual ApSupplier ApSupplier { get; set; }
        public virtual PorSupStkInfo PorSupStkInfo { get; set; }
    }
}
