//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvBuyer
    {
        public InvBuyer()
        {
            this.InvMasters = new HashSet<InvMaster>();
            this.PorMasterHdrs = new HashSet<PorMasterHdr>();
        }
    
        public string Buyer { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<InvMaster> InvMasters { get; set; }
        public virtual ICollection<PorMasterHdr> PorMasterHdrs { get; set; }
    }
}
