//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMaster
    {
        public InvMaster()
        {
            this.GrnDetails = new HashSet<GrnDetail>();
            this.InvStockTakes = new HashSet<InvStockTake>();
            this.InvWarehouses = new HashSet<InvWarehouse>();
            this.LotDetails = new HashSet<LotDetail>();
            this.PorMasterDetails = new HashSet<PorMasterDetail>();
            this.WipJobAllMats = new HashSet<WipJobAllMat>();
            this.WipMasters = new HashSet<WipMaster>();
            this.InvPrices = new HashSet<InvPrice>();
            this.InvNarrationHdrs = new HashSet<InvNarrationHdr>();
            this.BomOperations = new HashSet<BomOperation>();
            this.InvNarrations = new HashSet<InvNarration>();
            this.PorSupStkInfoes = new HashSet<PorSupStkInfo>();
        }
    
        public string StockCode { get; set; }
        public string Description { get; set; }
        public string LongDesc { get; set; }
        public string AlternateKey1 { get; set; }
        public string AlternateKey2 { get; set; }
        public string EccUser { get; set; }
        public string StockUom { get; set; }
        public string AlternateUom { get; set; }
        public string OtherUom { get; set; }
        public decimal ConvFactAltUom { get; set; }
        public string ConvMulDiv { get; set; }
        public decimal ConvFactOthUom { get; set; }
        public string MulDiv { get; set; }
        public decimal Mass { get; set; }
        public decimal Volume { get; set; }
        public decimal Decimals { get; set; }
        public string PriceCategory { get; set; }
        public string PriceMethod { get; set; }
        public string Supplier { get; set; }
        public decimal CycleCount { get; set; }
        public string ProductClass { get; set; }
        public string TaxCode { get; set; }
        public string OtherTaxCode { get; set; }
        public string ListPriceCode { get; set; }
        public string SerialMethod { get; set; }
        public string InterfaceFlag { get; set; }
        public string KitType { get; set; }
        public decimal LowLevelCode { get; set; }
        public string Buyer { get; set; }
        public string Planner { get; set; }
        public string TraceableType { get; set; }
        public string MpsFlag { get; set; }
        public string BulkIssueFlag { get; set; }
        public string AbcClass { get; set; }
        public decimal LeadTime { get; set; }
        public string StockMovementReq { get; set; }
        public string ClearingFlag { get; set; }
        public Nullable<System.DateTime> SupercessionDate { get; set; }
        public string AbcAnalysisReq { get; set; }
        public string AbcCostingReq { get; set; }
        public string CostUom { get; set; }
        public decimal MinPricePct { get; set; }
        public decimal LabourCost { get; set; }
        public decimal MaterialCost { get; set; }
        public decimal FixOverhead { get; set; }
        public decimal VariableOverhead { get; set; }
        public string PartCategory { get; set; }
        public string DrawOfficeNum { get; set; }
        public string WarehouseToUse { get; set; }
        public string BuyingRule { get; set; }
        public decimal SpecificGravity { get; set; }
        public decimal ImplosionNum { get; set; }
        public decimal Ebq { get; set; }
        public decimal ComponentCount { get; set; }
        public decimal FixTimePeriod { get; set; }
        public decimal PanSize { get; set; }
        public decimal DockToStock { get; set; }
        public string OutputMassFlag { get; set; }
        public decimal ShelfLife { get; set; }
        public string Version { get; set; }
        public string Release { get; set; }
        public decimal DemandTimeFence { get; set; }
        public string MakeToOrderFlag { get; set; }
        public decimal ManufLeadTime { get; set; }
        public string GrossReqRule { get; set; }
        public decimal PercentageYield { get; set; }
        public decimal AbcPreProd { get; set; }
        public decimal AbcManufacturing { get; set; }
        public decimal AbcSales { get; set; }
        public decimal AbcCumPreProd { get; set; }
        public decimal AbcCumManuf { get; set; }
        public string WipCtlGlCode { get; set; }
        public string ResourceCode { get; set; }
        public string GstTaxCode { get; set; }
        public string PrcInclGst { get; set; }
        public string SerEntryAtSale { get; set; }
        public string StpSelection { get; set; }
        public string UserField1 { get; set; }
        public decimal UserField2 { get; set; }
        public string UserField3 { get; set; }
        public string UserField4 { get; set; }
        public string UserField5 { get; set; }
        public string TariffCode { get; set; }
        public string SupplementaryUnit { get; set; }
        public string EbqPan { get; set; }
        public decimal StdLandedCost { get; set; }
        public string LctRequired { get; set; }
        public string StdLctRoute { get; set; }
        public string IssMultLotsFlag { get; set; }
        public string InclInStrValid { get; set; }
        public decimal StdLabCostsBill { get; set; }
        public string PhantomIfComp { get; set; }
        public string CountryOfOrigin { get; set; }
        public string StockOnHold { get; set; }
        public string StockOnHoldReason { get; set; }
        public string EccFlag { get; set; }
        public string StockAndAltUm { get; set; }
        public decimal AltUnitChar { get; set; }
        public string JobsOnHold { get; set; }
        public string JobHoldAllocs { get; set; }
        public string PurchOnHold { get; set; }
        public string SalesOnHold { get; set; }
        public string MaintOnHold { get; set; }
        public string BatchBill { get; set; }
        public string BlanketPoExists { get; set; }
        public string CallOffBpoExists { get; set; }
        public string DistWarehouseToUse { get; set; }
        public string JobClassification { get; set; }
        public decimal SubContractCost { get; set; }
        public Nullable<System.DateTime> DateStkAdded { get; set; }
        public string InspectionFlag { get; set; }
        public string SerialPrefix { get; set; }
        public string SerialSuffix { get; set; }
        public string ReturnableItem { get; set; }
        public string ProductGroup { get; set; }
        public string PriceType { get; set; }
        public string Basis { get; set; }
        public string ManualCostFlag { get; set; }
        public string ManufactureUom { get; set; }
        public decimal ConvFactMuM { get; set; }
        public string ManMulDiv { get; set; }
        public decimal LookAheadWin { get; set; }
        public decimal LoadingFactor { get; set; }
        public string SupplUnitCode { get; set; }
        public string StorageSecurity { get; set; }
        public string StorageHazard { get; set; }
        public string StorageCondition { get; set; }
        public decimal ProductShelfLife { get; set; }
        public decimal InternalShelfLife { get; set; }
        public byte[] TimeStamp { get; set; }
        public string AltMethodFlag { get; set; }
        public string AltSisoFlag { get; set; }
        public string AltReductionFlag { get; set; }
        public string WithTaxExpenseType { get; set; }
        public string UsesPrefSupplier { get; set; }
        public string PrdRecallFlag { get; set; }
        public string OnHoldReason { get; set; }
        public decimal SpecificGravity6 { get; set; }
        public decimal SuppUnitFactor { get; set; }
        public string SuppUnitsMulDiv { get; set; }
    
        public virtual ICollection<GrnDetail> GrnDetails { get; set; }
        public virtual ICollection<InvStockTake> InvStockTakes { get; set; }
        public virtual ICollection<InvWarehouse> InvWarehouses { get; set; }
        public virtual ICollection<LotDetail> LotDetails { get; set; }
        public virtual ICollection<PorMasterDetail> PorMasterDetails { get; set; }
        public virtual ICollection<WipJobAllMat> WipJobAllMats { get; set; }
        public virtual ICollection<WipMaster> WipMasters { get; set; }
        public virtual AdmTax AdmTax { get; set; }
        public virtual SalProductClassDe SalProductClassDe { get; set; }
        public virtual WipJobClass WipJobClass { get; set; }
        public virtual InvPrice InvPrice { get; set; }
        public virtual ICollection<InvPrice> InvPrices { get; set; }
        public virtual ICollection<InvNarrationHdr> InvNarrationHdrs { get; set; }
        public virtual ICollection<BomOperation> BomOperations { get; set; }
        public virtual ICollection<InvNarration> InvNarrations { get; set; }
        public virtual InvBuyer InvBuyer { get; set; }
        public virtual ApSupplier ApSupplier { get; set; }
        public virtual PorSupStkInfo PorSupStkInfo { get; set; }
        public virtual ICollection<PorSupStkInfo> PorSupStkInfoes { get; set; }
    }
}
