//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMultBin
    {
        public InvMultBin()
        {
            this.LotDetails = new HashSet<LotDetail>();
        }
    
        public string StockCode { get; set; }
        public string Warehouse { get; set; }
        public string Bin { get; set; }
        public decimal QtyOnHand1 { get; set; }
        public decimal QtyOnHand2 { get; set; }
        public decimal QtyOnHand3 { get; set; }
        public Nullable<System.DateTime> LastReceiptDate { get; set; }
        public Nullable<System.DateTime> LastIssueDate { get; set; }
        public decimal SoQtyToShip { get; set; }
        public string Note { get; set; }
        public decimal QtyDispatched { get; set; }
        public string OnHold { get; set; }
        public string OnHoldReason { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual InvMaster InvMaster { get; set; }
        public virtual InvStockTake InvStockTake { get; set; }
        public virtual InvWarehouse InvWarehouse { get; set; }
        public virtual InvStockTake InvStockTake1 { get; set; }
        public virtual ICollection<LotDetail> LotDetails { get; set; }
    }
}
