//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMaster_
    {
        public string StockCode { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> UnNo { get; set; }
        public string HazardClass { get; set; }
        public string Group1 { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Category { get; set; }
    }
}
