//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvNarration
    {
        public string StockCode { get; set; }
        public string TextType { get; set; }
        public string LanguageCode { get; set; }
        public decimal Line { get; set; }
        public string Text { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual InvMaster InvMaster { get; set; }
        public virtual InvNarrationHdr InvNarrationHdr { get; set; }
    }
}
