//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvPrice
    {
        public InvPrice()
        {
            this.InvMasters = new HashSet<InvMaster>();
        }
    
        public string StockCode { get; set; }
        public string PriceCode { get; set; }
        public decimal SellingPrice { get; set; }
        public string PriceBasis { get; set; }
        public string CommissionCode { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<InvMaster> InvMasters { get; set; }
        public virtual InvMaster InvMaster { get; set; }
    }
}
