//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvStockTake
    {
        public InvStockTake()
        {
            this.LotDetails = new HashSet<LotDetail>();
            this.WipJobAllMats = new HashSet<WipJobAllMat>();
        }
    
        public string Warehouse { get; set; }
        public string StockCode { get; set; }
        public string Bin { get; set; }
        public decimal OrigQtyOnHand { get; set; }
        public decimal QtyCaptured { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public string ProductClass { get; set; }
        public string Uom { get; set; }
        public string Reference { get; set; }
        public string PrintedFlag { get; set; }
        public decimal Decimals { get; set; }
        public decimal NumTimesCaptured { get; set; }
        public string CreatedBinFlag { get; set; }
        public decimal SelectionCost { get; set; }
        public byte[] TimeStamp { get; set; }
        public string DefaultBin { get; set; }
    
        public virtual InvWarehouse InvWarehouse { get; set; }
        public virtual InvWhBin InvWhBin { get; set; }
        public virtual ICollection<LotDetail> LotDetails { get; set; }
        public virtual ICollection<WipJobAllMat> WipJobAllMats { get; set; }
        public virtual InvMaster InvMaster { get; set; }
        public virtual SalProductClassDe SalProductClassDe { get; set; }
        public virtual InvWhControl InvWhControl { get; set; }
    }
}
