//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvWhBin
    {
        public InvWhBin()
        {
            this.LotDetails = new HashSet<LotDetail>();
            this.WipJobAllMats = new HashSet<WipJobAllMat>();
            this.InvStockTakes = new HashSet<InvStockTake>();
        }
    
        public string Warehouse { get; set; }
        public string Bin { get; set; }
        public decimal BinSeq { get; set; }
        public string WhArea { get; set; }
        public string BinType { get; set; }
        public string BinBarcode { get; set; }
        public string BinRfid { get; set; }
        public string ReservedStockCode { get; set; }
        public string BinOnHold { get; set; }
        public string OnHoldReason { get; set; }
        public string ActiveCycleCount { get; set; }
        public string AllowReplenish { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<LotDetail> LotDetails { get; set; }
        public virtual ICollection<WipJobAllMat> WipJobAllMats { get; set; }
        public virtual ICollection<InvStockTake> InvStockTakes { get; set; }
        public virtual InvWhControl InvWhControl { get; set; }
    }
}
