//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotDetail
    {
        public string StockCode { get; set; }
        public string Warehouse { get; set; }
        public string Lot { get; set; }
        public string Bin { get; set; }
        public decimal NextTrnLine { get; set; }
        public decimal OrigQtyReceived { get; set; }
        public decimal QtyOnHand { get; set; }
        public decimal QtyToShip { get; set; }
        public string Version { get; set; }
        public string Release { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string DrawOfficeNum { get; set; }
        public Nullable<System.DateTime> LastTrnDate { get; set; }
        public string ArchiveFilename { get; set; }
        public decimal QtyInTransit { get; set; }
        public string LotHoldFlag { get; set; }
        public string Note { get; set; }
        public string EccDummy { get; set; }
        public decimal QtyAwaitingCredit { get; set; }
        public decimal QtyReserved { get; set; }
        public string SupplierLot { get; set; }
        public decimal ProductShelfLife { get; set; }
        public decimal InternalShelfLife { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public Nullable<System.DateTime> SellByDate { get; set; }
        public Nullable<System.DateTime> InternalExpiryDate { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<System.DateTime> BestBeforeDate { get; set; }
        public string PrdRecallFlag { get; set; }
        public string ReasonCode { get; set; }
    
        public virtual InvWarehouse InvWarehouse { get; set; }
        public virtual InvWhBin InvWhBin { get; set; }
        public virtual InvStockTake InvStockTake { get; set; }
        public virtual InvMaster InvMaster { get; set; }
        public virtual InvWhControl InvWhControl { get; set; }
    }
}
