//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtDispatchVerification
    {
        public string DispatchNote { get; set; }
        public decimal DispatchNoteLine { get; set; }
        public string SalesOrder { get; set; }
        public decimal SalesOrderLine { get; set; }
        public string Lot { get; set; }
        public Nullable<decimal> StockQtyToShip { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> ScanDate { get; set; }
        public string VerificationComplete { get; set; }
    }
}
