//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtDistributionSetup
    {
        public string CompanyCode { get; set; }
        public bool SalesContractPricingServiceActive { get; set; }
        public string SalesContractPricingImportFilePath { get; set; }
        public string SalesContractPricingNotificationLetterPath { get; set; }
        public bool SalesContractPricingDoSalesOrderUpdate { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public string UserLastUpdated { get; set; }
        public bool SalesOrderPackagingRequired { get; set; }
        public Nullable<int> SalesOrderNumberOfCharacters { get; set; }
        public bool RequisitionSystemActive { get; set; }
        public string RequisitionFromEmailAddress { get; set; }
        public string RequisitionLocalCurrency { get; set; }
        public Nullable<decimal> RequisitionNotificationLimit { get; set; }
        public string RequisitionNotificationCurrency { get; set; }
        public Nullable<decimal> RequisitionNotificationExchangeRate { get; set; }
        public string RequisitionNotificationEmailAddress { get; set; }
        public string ViewUrlAddress { get; set; }
        public string ReqAPIAddress { get; set; }
        public Nullable<bool> ReqAutoApprovalContractPricing { get; set; }
        public string ReqAutoApprovalUserCode { get; set; }
        public Nullable<int> TrackId { get; set; }
        public Nullable<bool> RequisitionJobBossRequired { get; set; }
        public bool StockTakeServiceActive { get; set; }
        public Nullable<bool> ReqNumberPadZeros { get; set; }
        public string TransportReqPurchaseCategory { get; set; }
        public string TransportReqCostCentre { get; set; }
        public string TransportReqCategory { get; set; }
        public string TransportReqBranch { get; set; }
        public Nullable<bool> TransportSystemCreateReq { get; set; }
        public Nullable<bool> ReqProdClassGlCodeMandatory { get; set; }
        public Nullable<bool> ReqGlCodeFilterByBranch { get; set; }
        public string TransportReqUserCode { get; set; }
        public string TransportSystemRouteToUser { get; set; }
        public string TransportSystemNotificationEmail { get; set; }
        public Nullable<int> ReqEmailMaxReminders { get; set; }
        public Nullable<bool> ReqEmailReminders { get; set; }
        public Nullable<bool> SalesOrderClosureServiceActive { get; set; }
        public Nullable<decimal> SalesOrderClosureToleranceValue { get; set; }
        public string SalesOrderClosureEmail { get; set; }
        public Nullable<System.TimeSpan> SalesOrderClosureEmailSendTime { get; set; }
        public Nullable<System.DateTime> SalesOrderClosureLastEmailSentDate { get; set; }
        public string RequisitionSystemAdminEmail { get; set; }
    }
}
