//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtEmailSetting
    {
        public string EmailProgram { get; set; }
        public string SmtpHost { get; set; }
        public Nullable<int> SmtpPort { get; set; }
        public string FromAddress { get; set; }
        public string FromAddressPassword { get; set; }
        public Nullable<bool> EmailEnableSsl { get; set; }
    }
}
