//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtInvoiceExtractSetting
    {
        public string CustomerClass { get; set; }
        public string OutputFilePath { get; set; }
        public string SFTPUrl { get; set; }
        public string SFTPUsername { get; set; }
        public string SFTPPassword { get; set; }
        public string SFTPFolder { get; set; }
        public string SFTPPort { get; set; }
        public string ServiceScheduleMode { get; set; }
        public Nullable<System.TimeSpan> ServiceRunTime { get; set; }
        public string ServiceWeeklyDay { get; set; }
        public Nullable<int> ServiceMonthlyDate { get; set; }
        public string ServiceActive { get; set; }
        public Nullable<System.DateTime> LastRunDate { get; set; }
        public Nullable<int> ServiceIntervalMin { get; set; }
        public string ApiExtractUri { get; set; }
        public string SshHostKeyFingerprint { get; set; }
        public string SshPrivateKeyPath { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
    }
}
