//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtManufacturingSetup
    {
        public string CompanyCode { get; set; }
        public bool JobDelink { get; set; }
        public bool JobWarehouseUpdate { get; set; }
        public string JobWarehouse { get; set; }
        public bool MaterialWarehouseUpdate { get; set; }
        public string MaterialWarehouse { get; set; }
        public string MaterialWarehouseExclusion { get; set; }
        public bool SubContractMaterialWarehouseUpdate { get; set; }
        public string SubContractMaterialWarehouse { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public string UserLastUpdated { get; set; }
        public bool JobWorkCentreUpdate { get; set; }
        public bool PostingServiceActive { get; set; }
        public bool PostingServiceProcessBlanks { get; set; }
        public bool PostingServiceLabourPost { get; set; }
        public bool PostingServiceLabourRuntimeSetupTime { get; set; }
        public bool PostingServiceLabourGoodQty { get; set; }
        public bool PostingServiceLabourScrapQty { get; set; }
        public bool PostingServiceJobReceipt { get; set; }
        public string PostingServiceJobReceiptCostBasis { get; set; }
        public bool PostingServiceJobKitIssue { get; set; }
        public bool PostingServiceInvReceiptScrap { get; set; }
        public string PostingServiceInvReceiptScrapUom { get; set; }
        public string PostingServiceInvReceiptScrapStockCode { get; set; }
        public string PostingServiceInvReceiptScrapWarehouse { get; set; }
        public bool PostingServiceDowntimePosting { get; set; }
        public bool PostingServiceUpdateLineShipDate { get; set; }
        public Nullable<int> PostingServiceLineShipDateGraceDays { get; set; }
        public bool PostingServiceUpdateJobStartDate { get; set; }
        public Nullable<System.TimeSpan> PostingServiceJobStartDateUpdateTime { get; set; }
        public Nullable<int> PostingServiceJobStartDateUpdateIntervalHours { get; set; }
        public Nullable<System.DateTime> PostingServiceJobStartDateLastUpdate { get; set; }
        public string PostingServiceProductionEmail { get; set; }
        public string PostingServiceSalesEmail { get; set; }
        public string PostingServiceAdminEmail { get; set; }
        public Nullable<System.TimeSpan> PostingServiceEmailSendTime { get; set; }
        public Nullable<System.DateTime> PostingServiceEmailLastSendDate { get; set; }
        public bool PostingServiceLabourScrapSpecificIssue { get; set; }
        public string PostingServiceLabourScrapSpecificIssueStockClass { get; set; }
        public Nullable<bool> PackingTransferOutOnReceipt { get; set; }
        public string PackingTransferOutWarehouse { get; set; }
        public string PackingTransferOutBin { get; set; }
        public bool ScalesPostCompletedJob { get; set; }
        public Nullable<bool> MaterialIssueAllowLabelPrint { get; set; }
        public Nullable<bool> LabourPostingCapturePostLabour { get; set; }
        public Nullable<bool> LabourPostingCapturePostScrap { get; set; }
        public Nullable<bool> JobReceiptsPostJobCostRecalc { get; set; }
        public bool BatchPackingWeightRequired { get; set; }
    }
}
