//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtMasterCardBagging
    {
        public int Id { get; set; }
        public string WorkCentre { get; set; }
        public string HandleType { get; set; }
        public string SealType { get; set; }
        public string TopSeal { get; set; }
        public string BottomSeal { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> LeftGusset { get; set; }
        public Nullable<decimal> RightGusset { get; set; }
        public Nullable<decimal> TopGusset { get; set; }
        public Nullable<decimal> BottomGusset { get; set; }
        public Nullable<decimal> Lip { get; set; }
        public string HeaderSeal { get; set; }
        public Nullable<decimal> QuantityPerPack { get; set; }
        public Nullable<decimal> QuantityPerBale { get; set; }
        public Nullable<decimal> KgPerThousand { get; set; }
        public string HotMelt { get; set; }
        public bool DropTest { get; set; }
        public bool PerforationTest { get; set; }
        public string ToleranceOnLip { get; set; }
        public bool LeakProofTest { get; set; }
        public bool PrintCentral { get; set; }
        public string ToleranceOnWidth { get; set; }
        public string ToleranceRightGusset { get; set; }
        public string ToleranceOnLeftGusset { get; set; }
        public string ToleranceOnLength { get; set; }
        public string ToleranceBottomGusset { get; set; }
        public string ToleranceOnHeaderSeal { get; set; }
        public string StarPunch { get; set; }
        public string PunchHoles { get; set; }
        public bool OvalCutWithHandle { get; set; }
        public bool NoBlockingMisprints { get; set; }
        public bool PanelsFlush { get; set; }
        public bool StrongSideSeals { get; set; }
        public bool StrongSpineSeal { get; set; }
        public bool StrongTopBottomSeal { get; set; }
        public string SpecialInstructions { get; set; }
        public string SysproStockCode { get; set; }
    }
}
