//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtMasterCardSlitting
    {
        public int Id { get; set; }
        public string WorkCentre { get; set; }
        public string UnWindNo { get; set; }
        public Nullable<decimal> SlitWidth { get; set; }
        public string Tolerance { get; set; }
        public Nullable<decimal> KgPerReel { get; set; }
        public Nullable<decimal> MetersPerReel { get; set; }
        public Nullable<int> RollsUp { get; set; }
        public Nullable<int> NumberOfRolls { get; set; }
        public bool LowTension { get; set; }
        public string ToleranceOnStep { get; set; }
        public string CoreId { get; set; }
        public string CoreWall { get; set; }
        public string ReelODMin { get; set; }
        public string ReelODMax { get; set; }
        public Nullable<int> JoinsPerReel { get; set; }
        public bool FlushEvenWinding { get; set; }
        public bool NoMisprints { get; set; }
        public string ToleranceOnWedgeWeave { get; set; }
        public Nullable<decimal> PrintImageWidth { get; set; }
        public Nullable<decimal> PrintImageLength { get; set; }
        public string SpecialInstructions { get; set; }
        public string SysproStockCode { get; set; }
    }
}
