//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtMasterCardPrinting
    {
        public int Id { get; set; }
        public string WorkCentre { get; set; }
        public bool Surface { get; set; }
        public bool Reverse { get; set; }
        public string PrintDescription { get; set; }
        public string PrintImageWidth { get; set; }
        public string PrintImageLength { get; set; }
        public string ClearArea { get; set; }
        public Nullable<int> NumberColoursFront { get; set; }
        public Nullable<int> NumberColoursReverse { get; set; }
        public Nullable<decimal> CylinderCM { get; set; }
        public Nullable<int> NumberAround { get; set; }
        public Nullable<decimal> PitchOrStep { get; set; }
        public Nullable<int> NumberAccross { get; set; }
        public string Barcode { get; set; }
        public string BarcodeColour { get; set; }
        public Nullable<decimal> KgPerReel { get; set; }
        public Nullable<decimal> BagSizeWidth { get; set; }
        public Nullable<decimal> BagSizeLength { get; set; }
        public Nullable<decimal> MetersPerReel { get; set; }
        public Nullable<decimal> TotalMeters { get; set; }
        public Nullable<decimal> TotalKgs { get; set; }
        public bool Parev { get; set; }
        public bool Halaal { get; set; }
        public string RegNumber { get; set; }
        public string SpecialInstructions { get; set; }
        public Nullable<decimal> Micron { get; set; }
        public string SysproStockCode { get; set; }
    }
}
