//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtMasterCardWicketing
    {
        public int Id { get; set; }
        public string WorkCentre { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> LeftGusset { get; set; }
        public Nullable<decimal> RightGusset { get; set; }
        public Nullable<decimal> TopGusset { get; set; }
        public Nullable<decimal> BottomGusset { get; set; }
        public Nullable<decimal> Lip { get; set; }
        public string HeaderSeal { get; set; }
        public string ToleranceOnWidth { get; set; }
        public string ToleranceGusset { get; set; }
        public string ToleranceOnLength { get; set; }
        public Nullable<decimal> LipMinimum { get; set; }
        public bool NoBlockingMisprints { get; set; }
        public Nullable<decimal> BagsPerWicket { get; set; }
        public Nullable<decimal> BagsPerBox { get; set; }
        public Nullable<decimal> WicketHoleDistance { get; set; }
        public Nullable<decimal> BagOpening { get; set; }
        public bool Mitred { get; set; }
        public bool PrintPositionFlush { get; set; }
        public bool WicketHolePerforation { get; set; }
        public bool RefCodesTraceability { get; set; }
        public string COFResultsPRT { get; set; }
        public string COFResultsCLR { get; set; }
        public string SpecialInstructions { get; set; }
        public string SysproStockCode { get; set; }
    }
}
