//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtMasterCardExtrusion
    {
        public int Id { get; set; }
        public string WorkCentre { get; set; }
        public Nullable<decimal> Micron { get; set; }
        public Nullable<decimal> LayFlatWidth { get; set; }
        public Nullable<decimal> BUR { get; set; }
        public Nullable<decimal> TotalMass { get; set; }
        public Nullable<decimal> KgPerHour { get; set; }
        public Nullable<decimal> TotalMeters { get; set; }
        public string BlendAStockCode { get; set; }
        public string BlendBStockCode { get; set; }
        public string BlendCStockCode { get; set; }
        public Nullable<decimal> BlendAPerc { get; set; }
        public Nullable<decimal> BlendBPerc { get; set; }
        public Nullable<decimal> BlendCPerc { get; set; }
        public string MasterBatch { get; set; }
        public Nullable<decimal> RollsUp { get; set; }
        public Nullable<decimal> MassOfRolls { get; set; }
        public Nullable<decimal> NoOfRolls { get; set; }
        public Nullable<decimal> RollLength { get; set; }
        public string CoreWall { get; set; }
        public bool EdgeTrim { get; set; }
        public bool SingleWind { get; set; }
        public Nullable<decimal> DyneValue { get; set; }
        public Nullable<decimal> Width { get; set; }
        public bool NewJob { get; set; }
        public bool HighClarity { get; set; }
        public bool NoSlackEdge { get; set; }
        public bool NoGels { get; set; }
        public string GauageTolerance { get; set; }
        public string ShrinkRatioMD { get; set; }
        public string ShrinkRatioTD { get; set; }
        public bool LowTension { get; set; }
        public decimal SupplyPrintingWidth { get; set; }
        public bool TrimOnExtruder { get; set; }
        public bool NoMeltfracture { get; set; }
        public bool NoDieLines { get; set; }
        public string COFResultsTRD { get; set; }
        public string COFResultsCLR { get; set; }
        public bool EdgeWeave { get; set; }
        public string Notes { get; set; }
        public string SysproStockCode { get; set; }
        public string ExtrSlittingCode { get; set; }
        public string ProductType { get; set; }
        public string ProductSubType1 { get; set; }
        public Nullable<decimal> GenTreatment { get; set; }
        public string Industry { get; set; }
    }
}
