//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtMasterCardAttachment
    {
        public int AuditId { get; set; }
        public string StockCode { get; set; }
        public int Line { get; set; }
        public string FileName { get; set; }
        public byte[] Attachment { get; set; }
    }
}
