//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtMasterCardLamination
    {
        public int Id { get; set; }
        public string WorkCentre { get; set; }
        public string LamMethod { get; set; }
        public Nullable<decimal> Micron1 { get; set; }
        public Nullable<decimal> Micron2 { get; set; }
        public Nullable<decimal> Micron3 { get; set; }
        public Nullable<decimal> Substrate1 { get; set; }
        public Nullable<decimal> Substrate2 { get; set; }
        public Nullable<decimal> Substrate3 { get; set; }
        public Nullable<decimal> Width1 { get; set; }
        public Nullable<decimal> Width2 { get; set; }
        public Nullable<decimal> Width3 { get; set; }
        public Nullable<decimal> Mass1 { get; set; }
        public Nullable<decimal> Mass2 { get; set; }
        public Nullable<decimal> Mass3 { get; set; }
        public Nullable<decimal> Metres1 { get; set; }
        public Nullable<decimal> Metres2 { get; set; }
        public Nullable<decimal> Metres3 { get; set; }
        public string SpecialInstructions { get; set; }
        public string SysproStockCode { get; set; }
    }
}
