//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtPorDeliveryImport
    {
        public string DeliveryNote { get; set; }
        public string PurchaseOrder { get; set; }
        public decimal Line { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public Nullable<System.TimeSpan> FileTime { get; set; }
        public string RecordType { get; set; }
        public string RecordFunction { get; set; }
        public string StockCode { get; set; }
        public string SupplierStockCode { get; set; }
        public string Lot { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Uom { get; set; }
        public Nullable<decimal> Meters { get; set; }
        public Nullable<decimal> Grammage { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
        public string Scanned { get; set; }
        public string Grn { get; set; }
        public Nullable<System.DateTime> GrnDate { get; set; }
        public string GrnUser { get; set; }
    }
}
