//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtProductionPackLabelPrint
    {
        public string Job { get; set; }
        public string BatchId { get; set; }
        public int PackNo { get; set; }
        public string ExtruderNo { get; set; }
        public string ExtruderRoll { get; set; }
        public string PrintRoll { get; set; }
        public string PrintToWorkcentre { get; set; }
        public string OpCode { get; set; }
        public string BatchNo { get; set; }
        public string BaggingWorkcentre { get; set; }
        public string OpNo { get; set; }
        public Nullable<decimal> PackSize { get; set; }
        public Nullable<int> NoOfLabels { get; set; }
        public string Printer { get; set; }
        public string Packer { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
        public string Username { get; set; }
    }
}
