//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtProductionLabel
    {
        public string Job { get; set; }
        public string BatchId { get; set; }
        public Nullable<int> BatchSequence { get; set; }
        public Nullable<decimal> GrossQty { get; set; }
        public Nullable<decimal> NetQty { get; set; }
        public Nullable<int> NoOfLabels { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public string LabelPrinted { get; set; }
        public Nullable<int> ReprintCount { get; set; }
        public string LabelReceipted { get; set; }
        public string Journal { get; set; }
        public string ReceiptedBy { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string Customer { get; set; }
        public string Supervisor { get; set; }
        public string Operator { get; set; }
        public string Packer { get; set; }
        public string QC1 { get; set; }
        public string WorkCentre { get; set; }
        public string PalletNo { get; set; }
        public string Scanned { get; set; }
        public string ScannedBy { get; set; }
        public Nullable<System.DateTime> ScanDate { get; set; }
        public Nullable<decimal> Core { get; set; }
        public Nullable<decimal> Tare { get; set; }
        public string Reference { get; set; }
        public string PreviousWorkCentre { get; set; }
        public string Department { get; set; }
        public Nullable<int> ScaleModelId { get; set; }
        public string ErrorMessage { get; set; }
        public string PrintOpReference { get; set; }
        public string LotIssued { get; set; }
    }
}
