//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtProductionPalletWeight
    {
        public string Job { get; set; }
        public string PalletNo { get; set; }
        public Nullable<int> ScaleModelId { get; set; }
        public string StockCode { get; set; }
        public Nullable<decimal> GrossQty { get; set; }
        public Nullable<decimal> NetQty { get; set; }
        public Nullable<decimal> ScaleWeight { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> ScaleDate { get; set; }
    }
}
