//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtRequisitionDetail
    {
        public string Requisition { get; set; }
        public int Line { get; set; }
        public string StockCode { get; set; }
        public string Description { get; set; }
        public string Uom { get; set; }
        public string ProductClass { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string GlCode { get; set; }
        public string Site { get; set; }
        public string Job { get; set; }
        public string HierarchyCategory { get; set; }
        public string Supplier { get; set; }
        public Nullable<decimal> SupplierValue { get; set; }
        public string Warehouse { get; set; }
        public string TaxCode { get; set; }
        public string PurchaseOrder { get; set; }
        public Nullable<int> PoLine { get; set; }
        public string LineType { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CommentFromLine { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Operator { get; set; }
    
        public virtual mtRequisitionDetail mtRequisitionDetail1 { get; set; }
        public virtual mtRequisitionDetail mtRequisitionDetail2 { get; set; }
    }
}
