//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtReqRoutingTracking
    {
        public int Id { get; set; }
        public Nullable<System.Guid> MegasoftGuid { get; set; }
        public string Company { get; set; }
        public string Requisition { get; set; }
        public string Originator { get; set; }
        public string RoutedTo { get; set; }
        public Nullable<System.DateTime> DateRouted { get; set; }
        public string Username { get; set; }
        public string RouteNote { get; set; }
        public string GuidActive { get; set; }
        public Nullable<int> NoOfApprovals { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string ProcessApiRequest { get; set; }
    }
}
