//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtReason
    {
        public int ReasonId { get; set; }
        public string ReasonType { get; set; }
        public string ReasonCode { get; set; }
        public string Reason { get; set; }
    }
}
