//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtRequisitionDeletedQuote
    {
        public int Id { get; set; }
        public string Requisition { get; set; }
        public int Line { get; set; }
        public string Supplier { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Supplier1 { get; set; }
        public string Supplier2 { get; set; }
        public string Supplier3 { get; set; }
        public Nullable<decimal> SupplierPrice1 { get; set; }
        public Nullable<decimal> SupplierPrice2 { get; set; }
        public Nullable<decimal> SupplierPrice3 { get; set; }
        public string FilePath1 { get; set; }
        public string FilePath2 { get; set; }
        public string FilePath3 { get; set; }
        public string FileName1 { get; set; }
        public string FileName2 { get; set; }
        public string FileName3 { get; set; }
        public bool SupplierOverride { get; set; }
        public string SupplierOverrideReasonCode { get; set; }
        public string SupplierOverrideReason { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string DeletedBy { get; set; }
    }
}
