//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtRequisitionEmailLog
    {
        public int EmailId { get; set; }
        public string Requisition { get; set; }
        public string Supplier { get; set; }
        public string ToEmail { get; set; }
        public string CCEmail { get; set; }
        public string FromEmail { get; set; }
        public string Subject { get; set; }
        public string MessageBody { get; set; }
        public string AttachmentPath { get; set; }
        public string FileName { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
    }
}
