//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtReqPurchaseOrder
    {
        public string Company { get; set; }
        public string Requisition { get; set; }
        public int Line { get; set; }
        public string PurchaseOrder { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Username { get; set; }
    }
}
