//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtRequisitionDeletedLine
    {
        public int Id { get; set; }
        public string Requisition { get; set; }
        public int Line { get; set; }
        public string StockCode { get; set; }
        public string Description { get; set; }
        public string Uom { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string DeletedBy { get; set; }
        public string Reason { get; set; }
    }
}
