//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtReportMaster
    {
        public string Program { get; set; }
        public string Report { get; set; }
        public string ReportPath { get; set; }
        public string DisplayName { get; set; }
        public string ReportGroup { get; set; }
    }
}
