//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtScaleSetting
    {
        public int SettingId { get; set; }
        public Nullable<decimal> ReceiptTolerance { get; set; }
        public Nullable<int> LabelTextWidth { get; set; }
        public Nullable<int> LabelTextLines { get; set; }
    }
}
