//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtScale
    {
        public int ScaleModelId { get; set; }
        public string FriendlyName { get; set; }
        public string ScaleModelName { get; set; }
        public int SerialBaudRate { get; set; }
        public int SerialDataBits { get; set; }
        public int SerialHandshake { get; set; }
        public int SerialParity { get; set; }
        public int SerialStopBits { get; set; }
        public int SerialTerminator { get; set; }
        public string ScaleStringPrefix { get; set; }
        public int ScaleStartMassOrdinal { get; set; }
        public int ScaleMassOrdinalLength { get; set; }
        public int ScaleStartMassDecimal { get; set; }
        public int ScaleMassDecimalLength { get; set; }
        public Nullable<int> ScaleDataLength { get; set; }
        public Nullable<decimal> CurrWeight { get; set; }
        public string PrinterName { get; set; }
        public Nullable<decimal> Core { get; set; }
        public Nullable<decimal> Tare { get; set; }
        public string Warehouse { get; set; }
    }
}
