//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtShift
    {
        public int ShiftID { get; set; }
        public string Shift { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Reference { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<bool> NextDay { get; set; }
    }
}
