//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtSmartScanMatrix
    {
        public System.Guid SmartId { get; set; }
        public string Company { get; set; }
        public string Username { get; set; }
        public Nullable<int> TrnType { get; set; }
        public string SourceWarehouse { get; set; }
        public string SourceBin { get; set; }
        public string DestWarehouse { get; set; }
        public string DestBin { get; set; }
    }
}
