//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtSorScheduler
    {
        public string SalesOrder { get; set; }
        public decimal Line { get; set; }
        public Nullable<int> StockDays { get; set; }
        public Nullable<System.DateTime> DateSaved { get; set; }
        public string Username { get; set; }
    }
}
