//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtStereoSupplier
    {
        public string Supplier { get; set; }
        public string CustomerExpenseGlCode { get; set; }
        public string ProductClass { get; set; }
        public string Taxable { get; set; }
        public string TaxCode { get; set; }
        public string Email { get; set; }
        public string InternalExpenseGlCode { get; set; }
    }
}
