//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtStereoHdr
    {
        public int ReqNo { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string PlateCategory { get; set; }
        public string CustomerInvoice { get; set; }
        public string Invoice { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public string SalesOrder { get; set; }
        public string StockCode { get; set; }
        public string SupplierReference { get; set; }
        public string DesignReference { get; set; }
        public string Taxable { get; set; }
        public string Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string PrintDescription { get; set; }
        public Nullable<decimal> BagSize { get; set; }
        public Nullable<decimal> CylSlvSize { get; set; }
        public string Surface { get; set; }
        public Nullable<decimal> NumberAround { get; set; }
        public Nullable<decimal> NumberAcross { get; set; }
        public Nullable<decimal> NumberSetsRequired { get; set; }
        public string MaterialType { get; set; }
        public Nullable<decimal> Thickness { get; set; }
        public Nullable<decimal> NumberOfColoursFront { get; set; }
        public Nullable<decimal> NumberOfColoursReverse { get; set; }
        public string SpecialInstructions { get; set; }
        public string Quotation { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public string Barcode { get; set; }
        public string BarcodeColour { get; set; }
        public string Eyemark { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<int> NumberColours { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> DateProofRequired { get; set; }
        public Nullable<System.DateTime> DateStereosRequired { get; set; }
        public string ChargeCustomer { get; set; }
        public string ChargeTropic { get; set; }
        public string StereoType { get; set; }
        public Nullable<int> ChangePlate { get; set; }
        public string PoCreated { get; set; }
        public string PurchaseOrderRequired { get; set; }
        public string PurchaseOrder { get; set; }
        public string Variant { get; set; }
    }
}
