//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtStereoSetting
    {
        public int SettingId { get; set; }
        public string PurchasingCategory { get; set; }
        public string PurchasingDepartment { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<decimal> Tolerance { get; set; }
    }
}
