//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtStockLabel
    {
        public string StockCode { get; set; }
        public string Lot { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Warehouse { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
        public string Bin { get; set; }
    }
}
