//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtStockTakeCapture
    {
        public int ID { get; set; }
        public string Warehouse { get; set; }
        public string Bin { get; set; }
        public string StockCode { get; set; }
        public string Lot { get; set; }
        public Nullable<System.DateTime> LotExpiry { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string BinLocation { get; set; }
        public string SerialNumber { get; set; }
        public string Version { get; set; }
        public string Release { get; set; }
        public string TicketNumber { get; set; }
        public string Uom { get; set; }
        public Nullable<System.DateTime> CaptureDate { get; set; }
        public string Username { get; set; }
        public string Reference { get; set; }
    }
}
