//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtSupplierContractPricingColumnMapping
    {
        public string Username { get; set; }
        public string ContractReference { get; set; }
        public string Supplier { get; set; }
        public string StockCode { get; set; }
        public string StartDate { get; set; }
        public string ExpiryDate { get; set; }
        public string PurchasePrice { get; set; }
    }
}
