//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtTankMovementStaging
    {
        public System.Guid GUID { get; set; }
        public string Tank { get; set; }
        public string Description { get; set; }
        public string Tagname { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> Receipt { get; set; }
        public Nullable<decimal> Delivery { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
    }
}
