//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtTankLevelStaging
    {
        public System.Guid GUID { get; set; }
        public int EntryNo { get; set; }
        public string Tank { get; set; }
        public string Description { get; set; }
        public string Tagname { get; set; }
        public string TankType { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> StartVolumePerc { get; set; }
        public Nullable<decimal> EndVolumePerc { get; set; }
        public Nullable<decimal> StartVolumeTT { get; set; }
        public Nullable<decimal> EndVolumeTT { get; set; }
        public Nullable<decimal> StartVolumeST { get; set; }
        public Nullable<decimal> EndVolumeST { get; set; }
        public Nullable<decimal> StartVolumeRT { get; set; }
        public Nullable<decimal> EndVolumeRT { get; set; }
        public Nullable<decimal> TankCapacity { get; set; }
        public decimal FromTemperature { get; set; }
        public Nullable<decimal> ToTemperature { get; set; }
        public Nullable<decimal> StartDensityST { get; set; }
        public Nullable<decimal> EndDensityST { get; set; }
        public Nullable<decimal> StartDensityTT { get; set; }
        public Nullable<decimal> EndDensityTT { get; set; }
        public Nullable<decimal> StartDensityRT { get; set; }
        public Nullable<decimal> EndDensityRT { get; set; }
        public Nullable<decimal> StartLitresST { get; set; }
        public Nullable<decimal> EndLitresST { get; set; }
        public Nullable<decimal> StartLitresTT { get; set; }
        public Nullable<decimal> EndLitresTT { get; set; }
        public Nullable<decimal> StartLitresRT { get; set; }
        public Nullable<decimal> EndLitresRT { get; set; }
        public string BlendNo { get; set; }
        public Nullable<decimal> StartMassST { get; set; }
        public Nullable<decimal> EndMassST { get; set; }
        public Nullable<decimal> StartMassTT { get; set; }
        public Nullable<decimal> EndMassTT { get; set; }
        public Nullable<decimal> StartMassRT { get; set; }
        public Nullable<decimal> EndMassRT { get; set; }
        public Nullable<decimal> ReportingTemperature { get; set; }
        public string SGMethod { get; set; }
        public string Product { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
        public string strMessage { get; set; }
        public string Operator { get; set; }
    }
}
