//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtTankMaster
    {
        public string Tank { get; set; }
        public string Description { get; set; }
        public string Tagname { get; set; }
        public string Uom { get; set; }
        public string UomDescription { get; set; }
        public string TemperatureTagname { get; set; }
        public Nullable<decimal> TankCapacity { get; set; }
        public string TankType { get; set; }
        public string Product { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public string Operator { get; set; }
        public Nullable<decimal> StandardDensity { get; set; }
    }
}
