//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtTransportSetting
    {
        public int SettingId { get; set; }
        public string Department { get; set; }
        public string RequestedBy1 { get; set; }
        public string PurchaseCategory { get; set; }
    }
}
