//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtTransportWaybillHdr
    {
        public int TrackId { get; set; }
        public string Transporter { get; set; }
        public string VehicleReg { get; set; }
        public string Driver { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
        public string Username { get; set; }
    }
}
