//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtWipJobCostRecalcLog
    {
        public int Id { get; set; }
        public string Job { get; set; }
        public Nullable<decimal> ExpLabourOrig { get; set; }
        public Nullable<decimal> ExpMaterialOrig { get; set; }
        public Nullable<decimal> ExpLabourCurrent { get; set; }
        public Nullable<decimal> ExpMaterialCurrent { get; set; }
        public Nullable<System.DateTime> DateSaved { get; set; }
        public string Posted { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public Nullable<decimal> NewExpLabour { get; set; }
        public Nullable<decimal> NewExpMaterial { get; set; }
        public string ErrorMessage { get; set; }
        public string SysproUser { get; set; }
        public Nullable<decimal> QtyToMake { get; set; }
        public Nullable<decimal> JobReceiptQty { get; set; }
    }
}
