//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtWmsDeletedItem
    {
        public int Id { get; set; }
        public Nullable<int> WmsId { get; set; }
        public Nullable<int> WmsLine { get; set; }
        public Nullable<int> SalesOrderLine { get; set; }
        public string StockCode { get; set; }
        public string Lot { get; set; }
        public string PalletId { get; set; }
        public string ScanType { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> ReasonCode { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    }
}
