//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtWmsOrderDetail
    {
        public int WmsId { get; set; }
        public int WmsLine { get; set; }
        public int SalesOrderLine { get; set; }
        public string StockCode { get; set; }
        public string Bin { get; set; }
        public string Lot { get; set; }
        public string Serial { get; set; }
        public string PalletNo { get; set; }
        public string ScanType { get; set; }
        public Nullable<decimal> QuantityReleased { get; set; }
        public Nullable<decimal> QuantityPicked { get; set; }
        public string Picker { get; set; }
        public string ReleasedBy { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public Nullable<System.DateTime> DatePicked { get; set; }
        public string CheckoutDone { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
    }
}
