//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtWmsOrderMaster
    {
        public int WmsId { get; set; }
        public string SalesOrder { get; set; }
        public int SalesOrderLine { get; set; }
        public string StockCode { get; set; }
        public string Warehouse { get; set; }
        public string Uom { get; set; }
        public decimal SalesReleaseQty { get; set; }
        public string Comment { get; set; }
        public string SalesReleaseUser { get; set; }
        public Nullable<System.DateTime> SalesReleaseDate { get; set; }
        public string TraceableType { get; set; }
        public string WmsStatus { get; set; }
        public string DispatchNote { get; set; }
        public string ExpressPicker { get; set; }
    }
}
