//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorMasterHdr
    {
        public PorMasterHdr()
        {
            this.PorMasterDetails = new HashSet<PorMasterDetail>();
            this.GrnDetails = new HashSet<GrnDetail>();
        }
    
        public string PurchaseOrder { get; set; }
        public decimal NextDetailLine { get; set; }
        public string OrderStatus { get; set; }
        public string ActiveFlag { get; set; }
        public string CancelledFlag { get; set; }
        public string Supplier { get; set; }
        public Nullable<System.DateTime> OrderEntryDate { get; set; }
        public Nullable<System.DateTime> OrderDueDate { get; set; }
        public Nullable<System.DateTime> DateLastDocPrt { get; set; }
        public Nullable<System.DateTime> MemoDate { get; set; }
        public string MemoCode { get; set; }
        public string OrderType { get; set; }
        public string SupplierClass { get; set; }
        public string Customer { get; set; }
        public string CustomerPoNumber { get; set; }
        public string PaymentTerms { get; set; }
        public string ShippingInstrs { get; set; }
        public string Warehouse { get; set; }
        public decimal DiscPct1 { get; set; }
        public decimal DiscPct2 { get; set; }
        public decimal DiscPct3 { get; set; }
        public string Currency { get; set; }
        public string TaxStatus { get; set; }
        public decimal PrintCount { get; set; }
        public decimal AmendedCount { get; set; }
        public Nullable<System.DateTime> DatePoCompleted { get; set; }
        public decimal ExchangeRate { get; set; }
        public string MulDiv { get; set; }
        public string ExchRateFixed { get; set; }
        public string Nationality { get; set; }
        public string TermsCode { get; set; }
        public string UserConfirmation { get; set; }
        public string EdiPoFlag { get; set; }
        public string EdiExtractFlag { get; set; }
        public string EdiActionFlag { get; set; }
        public string Buyer { get; set; }
        public string EdiConfirmation { get; set; }
        public string FaxDocument { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryAddr1 { get; set; }
        public string DeliveryAddr2 { get; set; }
        public string DeliveryAddr3 { get; set; }
        public string DeliveryAddr3Loc { get; set; }
        public string DeliveryAddr4 { get; set; }
        public string DeliveryAddr5 { get; set; }
        public string PostalCode { get; set; }
        public decimal DeliveryGpsLat { get; set; }
        public decimal DeliveryGpsLong { get; set; }
        public string DocumentFormat { get; set; }
        public string ContractNumber { get; set; }
        public string User1 { get; set; }
        public string DeliveryMethod { get; set; }
        public string AutoVoucherReqd { get; set; }
        public string LanguageCode { get; set; }
        public string AutoUpdatePo { get; set; }
        public string State { get; set; }
        public string CountyZip { get; set; }
        public string City { get; set; }
        public string ShippingLocation { get; set; }
        public byte[] TimeStamp { get; set; }
        public string DeliveryTerms { get; set; }
        public string IncludeInMrp { get; set; }
        public string Email { get; set; }
        public string RegimeCode { get; set; }
        public string PortArrival { get; set; }
    
        public virtual ICollection<PorMasterDetail> PorMasterDetails { get; set; }
        public virtual ICollection<GrnDetail> GrnDetails { get; set; }
        public virtual InvWhControl InvWhControl { get; set; }
        public virtual InvBuyer InvBuyer { get; set; }
        public virtual ApSupplier ApSupplier { get; set; }
    }
}
