//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorMasterDetail_
    {
        public string PurchaseOrder { get; set; }
        public decimal Line { get; set; }
        public Nullable<decimal> Width { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<decimal> Length { get; set; }
    }
}
