//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorMasterHdr_
    {
        public string PurchaseOrder { get; set; }
        public string Ship { get; set; }
        public string Delivery { get; set; }
        public string Category { get; set; }
        public byte[] TimeStamp { get; set; }
        public string RequestedBy1 { get; set; }
        public string PurchDepartment { get; set; }
        public string PurchaseCategory { get; set; }
        public string RequestedBy2 { get; set; }
        public string RequestedBy3 { get; set; }
        public string Machine { get; set; }
        public string Fitted { get; set; }
        public string Comment { get; set; }
        public string PlateCategory { get; set; }
    }
}
