//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqDetail
    {
        public string Originator { get; set; }
        public string Requisition { get; set; }
        public decimal Line { get; set; }
        public string ReqnStatus { get; set; }
        public string StockCode { get; set; }
        public string StockDescription { get; set; }
        public decimal OrderQty { get; set; }
        public string OrderUom { get; set; }
        public Nullable<System.DateTime> DateReqnRaised { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string ReasonForReqn { get; set; }
        public string Supplier { get; set; }
        public decimal Price { get; set; }
        public string PriceUom { get; set; }
        public decimal DiscPct1 { get; set; }
        public decimal DiscPct2 { get; set; }
        public decimal DiscPct3 { get; set; }
        public string DiscountCode { get; set; }
        public string Warehouse { get; set; }
        public string SupCatalogueNum { get; set; }
        public string Job { get; set; }
        public string JobLine { get; set; }
        public string GlCode { get; set; }
        public string ProductClass { get; set; }
        public string TaxCode { get; set; }
        public string Customer { get; set; }
        public string CustomerPoNumber { get; set; }
        public string CapexNum { get; set; }
        public string ReqnOnHoldFlag { get; set; }
        public string ReasonForHold { get; set; }
        public string HoldUser { get; set; }
        public string ConfirmedPoNum { get; set; }
        public decimal ConfirmedPoLine { get; set; }
        public Nullable<System.DateTime> DatePoConfirmed { get; set; }
        public string Buyer { get; set; }
        public string CurrentHolder { get; set; }
        public decimal HoldersRouteNum { get; set; }
        public Nullable<System.DateTime> DateActioned { get; set; }
        public string ReceiptFlag { get; set; }
        public Nullable<System.DateTime> DateLastReceipt { get; set; }
        public string AckReceiptFlag { get; set; }
        public string SalesOrder { get; set; }
        public decimal SalesOrderLine { get; set; }
        public string PrintedFlag { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string HierHead { get; set; }
        public string Section1 { get; set; }
        public string Section2 { get; set; }
        public string Section3 { get; set; }
        public string Section4 { get; set; }
        public decimal SubOperationNum { get; set; }
        public string Quote { get; set; }
        public decimal QuoteVersion { get; set; }
        public decimal QuoteLineNum { get; set; }
        public string InspectNonStkRec { get; set; }
        public string DocumentFormat { get; set; }
        public string EccHold { get; set; }
        public string Version { get; set; }
        public string Release { get; set; }
        public string UserCode { get; set; }
        public string BpoApproved { get; set; }
        public string Operator { get; set; }
        public string CurrentOperator { get; set; }
        public string AssetFlag { get; set; }
        public decimal CapexLine { get; set; }
        public string CapexCode { get; set; }
        public string RequisitionType { get; set; }
        public string IssueWarehouse { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string SelectionCode { get; set; }
        public string SelectionType { get; set; }
        public string AutoVoucherReqd { get; set; }
        public string ShippingLocation { get; set; }
        public byte[] TimeStamp { get; set; }
        public string DeliveryTerms { get; set; }
        public string IncludeInMrp { get; set; }
        public string WithTaxExpenseType { get; set; }
    
        public virtual AdmTax AdmTax { get; set; }
        public virtual ApSupplier ApSupplier { get; set; }
        public virtual InvBuyer InvBuyer { get; set; }
        public virtual InvMaster InvMaster { get; set; }
        public virtual InvWarehouse InvWarehouse { get; set; }
        public virtual InvWhControl InvWhControl { get; set; }
        public virtual PorSupStkInfo PorSupStkInfo { get; set; }
        public virtual SalProductClassDe SalProductClassDe { get; set; }
        public virtual WipMaster WipMaster { get; set; }
    }
}
