//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalArea
    {
        public SalArea()
        {
            this.ApSuppliers = new HashSet<ApSupplier>();
            this.InvWhControls = new HashSet<InvWhControl>();
        }
    
        public string Area { get; set; }
        public string Description { get; set; }
        public string TaxCode { get; set; }
        public string ProvTaxFlag { get; set; }
        public string AreaGstCode { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual AdmTax AdmTax { get; set; }
        public virtual ICollection<ApSupplier> ApSuppliers { get; set; }
        public virtual ICollection<InvWhControl> InvWhControls { get; set; }
    }
}
