//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalBranch
    {
        public SalBranch()
        {
            this.InvWhControls = new HashSet<InvWhControl>();
            this.SalSalespersons = new HashSet<SalSalesperson>();
        }
    
        public string Branch { get; set; }
        public string Description { get; set; }
        public string BranchAddr0Build { get; set; }
        public string BranchAddr1 { get; set; }
        public string BranchAddr2 { get; set; }
        public string BranchAddr2Loc { get; set; }
        public string BranchAddr3 { get; set; }
        public string BranchAddr3Country { get; set; }
        public string BranchPostalCode { get; set; }
        public decimal BranchGpsLat { get; set; }
        public decimal BranchGpsLong { get; set; }
        public string FrtCosAcc { get; set; }
        public string SalesCtlAcc { get; set; }
        public string CosCtlAcc { get; set; }
        public string FrtSalesAcc { get; set; }
        public string FinChargeAcc { get; set; }
        public string RoundingAcc { get; set; }
        public string SalesTaxAcc { get; set; }
        public string FstAcc { get; set; }
        public string DepositAcc { get; set; }
        public string PrefixNextInv { get; set; }
        public decimal NextInvoice { get; set; }
        public decimal NextCreditNote { get; set; }
        public decimal NextDebitNote { get; set; }
        public string PrefixNextSo { get; set; }
        public decimal NextSalesOrder { get; set; }
        public decimal NextSoCrNote { get; set; }
        public decimal NextSoDbNote { get; set; }
        public decimal NextDelNote { get; set; }
        public string PrefixNextRma { get; set; }
        public decimal NextRma { get; set; }
        public string Nationality { get; set; }
        public decimal NextCreditDisc { get; set; }
        public decimal NextDebitDisc { get; set; }
        public string LanguageCode { get; set; }
        public string QuotePrefix { get; set; }
        public decimal NextQuote { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<InvWhControl> InvWhControls { get; set; }
        public virtual ICollection<SalSalesperson> SalSalespersons { get; set; }
    }
}
