//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalProductClassDe
    {
        public SalProductClassDe()
        {
            this.BomCostCentres = new HashSet<BomCostCentre>();
            this.BomWorkCentres = new HashSet<BomWorkCentre>();
            this.GrnDetails = new HashSet<GrnDetail>();
            this.InvMasters = new HashSet<InvMaster>();
            this.InvStockTakes = new HashSet<InvStockTake>();
            this.PorMasterDetails = new HashSet<PorMasterDetail>();
        }
    
        public string ProductClass { get; set; }
        public string Description { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<BomCostCentre> BomCostCentres { get; set; }
        public virtual ICollection<BomWorkCentre> BomWorkCentres { get; set; }
        public virtual ICollection<GrnDetail> GrnDetails { get; set; }
        public virtual ICollection<InvMaster> InvMasters { get; set; }
        public virtual ICollection<InvStockTake> InvStockTakes { get; set; }
        public virtual ICollection<PorMasterDetail> PorMasterDetails { get; set; }
    }
}
