//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    
    public partial class sp_GetKitMaterialToIssue_Result1
    {
        public string Job { get; set; }
        public string Warehouse { get; set; }
        public string StockCode { get; set; }
        public string Line { get; set; }
        public Nullable<decimal> ProdQty { get; set; }
        public Nullable<decimal> QtyOnHand { get; set; }
        public Nullable<decimal> MaterialToPost { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<decimal> UnitQtyReqd { get; set; }
        public Nullable<decimal> ScrapQuantity { get; set; }
        public Nullable<decimal> QtyIssued { get; set; }
        public string TraceableType { get; set; }
    }
}
