//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SysproEntities : DbContext
    {
        public SysproEntities()
            : base("name=SysproEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdmTax> AdmTaxes { get; set; }
        public DbSet<ApBranch> ApBranches { get; set; }
        public DbSet<ApSupplier> ApSuppliers { get; set; }
        public DbSet<GenMaster> GenMasters { get; set; }
        public DbSet<InvMaster> InvMasters { get; set; }
        public DbSet<InvMaster_> InvMaster_ { get; set; }
        public DbSet<mtBranchSite> mtBranchSites { get; set; }
        public DbSet<mtBranchSiteDept> mtBranchSiteDepts { get; set; }
        public DbSet<mtEnetSetting> mtEnetSettings { get; set; }
        public DbSet<mtInvBranch> mtInvBranches { get; set; }
        public DbSet<mtInvMaster> mtInvMasters { get; set; }
        public DbSet<mtProductClass> mtProductClasses { get; set; }
        public DbSet<mtPurchaseOrderAnalysisCat> mtPurchaseOrderAnalysisCats { get; set; }
        public DbSet<mtRequisitionComment> mtRequisitionComments { get; set; }
        public DbSet<mtRequisitionEmailLog> mtRequisitionEmailLogs { get; set; }
        public DbSet<mtRequisitionSetting> mtRequisitionSettings { get; set; }
        public DbSet<mtRequisitionStatu> mtRequisitionStatus { get; set; }
        public DbSet<PorMasterDetail> PorMasterDetails { get; set; }
        public DbSet<PorMasterHdr> PorMasterHdrs { get; set; }
        public DbSet<WipMaster> WipMasters { get; set; }
        public DbSet<InvWarehouse> InvWarehouses { get; set; }
        public DbSet<InvWhControl> InvWhControls { get; set; }
        public DbSet<LotDetail> LotDetails { get; set; }
        public DbSet<SalArea> SalAreas { get; set; }
        public DbSet<SalBranch> SalBranches { get; set; }
        public DbSet<SalSalesperson> SalSalespersons { get; set; }
        public DbSet<InvWarehouse_> InvWarehouse_ { get; set; }
        public DbSet<TblArTerm> TblArTerms { get; set; }
        public DbSet<TblCurrency> TblCurrencies { get; set; }
        public DbSet<TblCustomerClass> TblCustomerClasses { get; set; }
        public DbSet<TblSoBuyingGroup> TblSoBuyingGroups { get; set; }
        public DbSet<TblSoShipInst> TblSoShipInsts { get; set; }
        public DbSet<TblSoType> TblSoTypes { get; set; }
        public DbSet<mtRequisitionAudit> mtRequisitionAudits { get; set; }
        public DbSet<mtGrnInvoiceAudit> mtGrnInvoiceAudits { get; set; }
        public DbSet<mtBuyerStatsFilter> mtBuyerStatsFilters { get; set; }
        public DbSet<TblSoStdCom> TblSoStdComs { get; set; }
        public DbSet<mtSupplierContact> mtSupplierContacts { get; set; }
        public DbSet<mtReason> mtReasons { get; set; }
        public DbSet<mtInvContractPricing> mtInvContractPricings { get; set; }
        public DbSet<mtRequisitionDeletedLine> mtRequisitionDeletedLines { get; set; }
        public DbSet<mtRequisitionDeletedQuote> mtRequisitionDeletedQuotes { get; set; }
        public DbSet<mtRequisitionQuote> mtRequisitionQuotes { get; set; }
        public DbSet<mtSupplierContractPrice> mtSupplierContractPrices { get; set; }
        public DbSet<AdmFormData> AdmFormDatas { get; set; }
        public DbSet<mtRequisitionHeader> mtRequisitionHeaders { get; set; }
        public DbSet<mtRequisitionTextLine> mtRequisitionTextLines { get; set; }
        public DbSet<mtRequisitionDetail> mtRequisitionDetails { get; set; }
        public DbSet<AdmFormList> AdmFormLists { get; set; }
        public DbSet<mtPeriodControl> mtPeriodControls { get; set; }
        public DbSet<AdmFormControl> AdmFormControls { get; set; }
        public DbSet<vwApSupplier> vwApSuppliers { get; set; }
        public DbSet<AdmFormValidation> AdmFormValidations { get; set; }
        public DbSet<mtGrnDetail> mtGrnDetails { get; set; }
        public DbSet<mtBeeSupplierAudit> mtBeeSupplierAudits { get; set; }
        public DbSet<mtBeeEmailLog> mtBeeEmailLogs { get; set; }
        public DbSet<mtBeePreference> mtBeePreferences { get; set; }
        public DbSet<mtBranch> mtBranches { get; set; }
        public DbSet<ApSupplier_> ApSupplier_ { get; set; }
        public DbSet<CusGenMaster_> CusGenMaster_ { get; set; }
        public DbSet<mtDepartment> mtDepartments { get; set; }
        public DbSet<mtApSupplier> mtApSuppliers { get; set; }
    
        public virtual ObjectResult<sp_GetAllStockCodes_Result> sp_GetAllStockCodes(string filterText)
        {
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllStockCodes_Result>("sp_GetAllStockCodes", filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetAllSuppliers_Result> sp_GetAllSuppliers(string filterText)
        {
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllSuppliers_Result>("sp_GetAllSuppliers", filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetApBranch_Result> sp_GetApBranch()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetApBranch_Result>("sp_GetApBranch");
        }
    
        public virtual ObjectResult<sp_GetApTerms_Result> sp_GetApTerms()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetApTerms_Result>("sp_GetApTerms");
        }
    
        public virtual ObjectResult<sp_GetAuthorizationGlCodes_Result> sp_GetAuthorizationGlCodes(string company, string username)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAuthorizationGlCodes_Result>("sp_GetAuthorizationGlCodes", companyParameter, usernameParameter);
        }
    
        public virtual ObjectResult<sp_GetBranchAccess_Result> sp_GetBranchAccess(string company, string @operator)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var operatorParameter = @operator != null ?
                new ObjectParameter("Operator", @operator) :
                new ObjectParameter("Operator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBranchAccess_Result>("sp_GetBranchAccess", companyParameter, operatorParameter);
        }
    
        public virtual ObjectResult<sp_GetBranchByStockCode_Result> sp_GetBranchByStockCode(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBranchByStockCode_Result>("sp_GetBranchByStockCode", stockCodeParameter);
        }
    
        public virtual ObjectResult<sp_GetBranchSiteByUser_Result> sp_GetBranchSiteByUser(string company, string @operator)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var operatorParameter = @operator != null ?
                new ObjectParameter("Operator", @operator) :
                new ObjectParameter("Operator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBranchSiteByUser_Result>("sp_GetBranchSiteByUser", companyParameter, operatorParameter);
        }
    
        public virtual ObjectResult<sp_GetCategoryByGlCode_Result> sp_GetCategoryByGlCode(string glCode, string filterText)
        {
            var glCodeParameter = glCode != null ?
                new ObjectParameter("GlCode", glCode) :
                new ObjectParameter("GlCode", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCategoryByGlCode_Result>("sp_GetCategoryByGlCode", glCodeParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetCategoryByJob_Result> sp_GetCategoryByJob(string job, string filterText)
        {
            var jobParameter = job != null ?
                new ObjectParameter("Job", job) :
                new ObjectParameter("Job", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCategoryByJob_Result>("sp_GetCategoryByJob", jobParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetCommentLinesForPo_Result> sp_GetCommentLinesForPo(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetCommentLinesForPo_Result>("sp_GetCommentLinesForPo", requisitionParameter);
        }
    
        public virtual ObjectResult<sp_GetContractPricingByStockCode_Result> sp_GetContractPricingByStockCode(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetContractPricingByStockCode_Result>("sp_GetContractPricingByStockCode", stockCodeParameter);
        }
    
        public virtual ObjectResult<sp_GetGlCodes_Result> sp_GetGlCodes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGlCodes_Result>("sp_GetGlCodes");
        }
    
        public virtual ObjectResult<sp_GetGlCodesByBranch_Result> sp_GetGlCodesByBranch(string branch, string site, string filterText)
        {
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGlCodesByBranch_Result>("sp_GetGlCodesByBranch", branchParameter, siteParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetGlCodesByBranchSite_Result> sp_GetGlCodesByBranchSite(string branch, string site, string username, string company, string filterText)
        {
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGlCodesByBranchSite_Result>("sp_GetGlCodesByBranchSite", branchParameter, siteParameter, usernameParameter, companyParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetGlCodesByCostCode_Result> sp_GetGlCodesByCostCode(string company, string username, string costCode)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var costCodeParameter = costCode != null ?
                new ObjectParameter("CostCode", costCode) :
                new ObjectParameter("CostCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGlCodesByCostCode_Result>("sp_GetGlCodesByCostCode", companyParameter, usernameParameter, costCodeParameter);
        }
    
        public virtual ObjectResult<sp_GetGlCodesByReportIndex_Result> sp_GetGlCodesByReportIndex(string company, string username, string reportIndex2)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var reportIndex2Parameter = reportIndex2 != null ?
                new ObjectParameter("ReportIndex2", reportIndex2) :
                new ObjectParameter("ReportIndex2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGlCodesByReportIndex_Result>("sp_GetGlCodesByReportIndex", companyParameter, usernameParameter, reportIndex2Parameter);
        }
    
        public virtual ObjectResult<sp_GetGrnEnquiryHeader_Result> sp_GetGrnEnquiryHeader(string username, string company, string filterText)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGrnEnquiryHeader_Result>("sp_GetGrnEnquiryHeader", usernameParameter, companyParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetGrnLinesForInvoicing_Result> sp_GetGrnLinesForInvoicing(string grn)
        {
            var grnParameter = grn != null ?
                new ObjectParameter("Grn", grn) :
                new ObjectParameter("Grn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGrnLinesForInvoicing_Result>("sp_GetGrnLinesForInvoicing", grnParameter);
        }
    
        public virtual ObjectResult<sp_GetGrnListForInvoicing_Result> sp_GetGrnListForInvoicing(string username, string company)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGrnListForInvoicing_Result>("sp_GetGrnListForInvoicing", usernameParameter, companyParameter);
        }
    
        public virtual ObjectResult<sp_GetGrnTotals_Result> sp_GetGrnTotals(string grn)
        {
            var grnParameter = grn != null ?
                new ObjectParameter("Grn", grn) :
                new ObjectParameter("Grn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGrnTotals_Result>("sp_GetGrnTotals", grnParameter);
        }
    
        public virtual ObjectResult<sp_GetInvoiceDetailsByGrn_Result> sp_GetInvoiceDetailsByGrn(string grn)
        {
            var grnParameter = grn != null ?
                new ObjectParameter("Grn", grn) :
                new ObjectParameter("Grn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetInvoiceDetailsByGrn_Result>("sp_GetInvoiceDetailsByGrn", grnParameter);
        }
    
        public virtual ObjectResult<sp_GetInvoicesForReview_Result> sp_GetInvoicesForReview(Nullable<int> authorisationLevel)
        {
            var authorisationLevelParameter = authorisationLevel.HasValue ?
                new ObjectParameter("AuthorisationLevel", authorisationLevel) :
                new ObjectParameter("AuthorisationLevel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetInvoicesForReview_Result>("sp_GetInvoicesForReview", authorisationLevelParameter);
        }
    
        public virtual ObjectResult<sp_GetJobsByGlCode_Result> sp_GetJobsByGlCode(string glCode, string filterText)
        {
            var glCodeParameter = glCode != null ?
                new ObjectParameter("GlCode", glCode) :
                new ObjectParameter("GlCode", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetJobsByGlCode_Result>("sp_GetJobsByGlCode", glCodeParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetJournalsToUpdate_Result> sp_GetJournalsToUpdate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetJournalsToUpdate_Result>("sp_GetJournalsToUpdate");
        }
    
        public virtual ObjectResult<sp_GetNextGrnNumber_Result> sp_GetNextGrnNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetNextGrnNumber_Result>("sp_GetNextGrnNumber");
        }
    
        public virtual ObjectResult<sp_GetPoLinesForMaterialAllocation_Result> sp_GetPoLinesForMaterialAllocation(string grn)
        {
            var grnParameter = grn != null ?
                new ObjectParameter("Grn", grn) :
                new ObjectParameter("Grn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPoLinesForMaterialAllocation_Result>("sp_GetPoLinesForMaterialAllocation", grnParameter);
        }
    
        public virtual ObjectResult<sp_GetPostingErrors_Result> sp_GetPostingErrors(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<bool> errorsOnly)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var errorsOnlyParameter = errorsOnly.HasValue ?
                new ObjectParameter("ErrorsOnly", errorsOnly) :
                new ObjectParameter("ErrorsOnly", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPostingErrors_Result>("sp_GetPostingErrors", fromDateParameter, toDateParameter, errorsOnlyParameter);
        }
    
        public virtual ObjectResult<sp_GetPostingPeriod_Result> sp_GetPostingPeriod(Nullable<System.DateTime> deliveryDate)
        {
            var deliveryDateParameter = deliveryDate.HasValue ?
                new ObjectParameter("DeliveryDate", deliveryDate) :
                new ObjectParameter("DeliveryDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPostingPeriod_Result>("sp_GetPostingPeriod", deliveryDateParameter);
        }
    
        public virtual ObjectResult<sp_GetProductClassLimits_Result> sp_GetProductClassLimits(string company, string username)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProductClassLimits_Result>("sp_GetProductClassLimits", companyParameter, usernameParameter);
        }
    
        public virtual ObjectResult<sp_GetPurchaseOrderLines_Result> sp_GetPurchaseOrderLines(string purchaseOrder)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPurchaseOrderLines_Result>("sp_GetPurchaseOrderLines", purchaseOrderParameter);
        }
    
        public virtual ObjectResult<sp_GetPurchaseOrderLinesForGrn_Result> sp_GetPurchaseOrderLinesForGrn(string purchaseOrder, string grn)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            var grnParameter = grn != null ?
                new ObjectParameter("Grn", grn) :
                new ObjectParameter("Grn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPurchaseOrderLinesForGrn_Result>("sp_GetPurchaseOrderLinesForGrn", purchaseOrderParameter, grnParameter);
        }
    
        public virtual ObjectResult<sp_GetPurchaseOrderReport_Result> sp_GetPurchaseOrderReport(string purchaseOrder)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPurchaseOrderReport_Result>("sp_GetPurchaseOrderReport", purchaseOrderParameter);
        }
    
        public virtual ObjectResult<sp_GetRequestForQuoteReport_Result> sp_GetRequestForQuoteReport(string requisition, string supplier)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            var supplierParameter = supplier != null ?
                new ObjectParameter("Supplier", supplier) :
                new ObjectParameter("Supplier", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequestForQuoteReport_Result>("sp_GetRequestForQuoteReport", requisitionParameter, supplierParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionAuthorizerByUser_Result> sp_GetRequisitionAuthorizerByUser(string requisition, string company, string username)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionAuthorizerByUser_Result>("sp_GetRequisitionAuthorizerByUser", requisitionParameter, companyParameter, usernameParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionAuthorizers_Result> sp_GetRequisitionAuthorizers(string requisition, string company)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionAuthorizers_Result>("sp_GetRequisitionAuthorizers", requisitionParameter, companyParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionComments_Result> sp_GetRequisitionComments(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionComments_Result>("sp_GetRequisitionComments", requisitionParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionHeader_Result> sp_GetRequisitionHeader(string username, string company, string filterText)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionHeader_Result>("sp_GetRequisitionHeader", usernameParameter, companyParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionLines_Result> sp_GetRequisitionLines(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionLines_Result>("sp_GetRequisitionLines", requisitionParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionList_Result> sp_GetRequisitionList(string company, string username, Nullable<bool> isAdmin, Nullable<bool> isRequisitioner, Nullable<bool> isBuyer, Nullable<bool> isAuthorizer, Nullable<bool> viewOnly)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("isAdmin", isAdmin) :
                new ObjectParameter("isAdmin", typeof(bool));
    
            var isRequisitionerParameter = isRequisitioner.HasValue ?
                new ObjectParameter("isRequisitioner", isRequisitioner) :
                new ObjectParameter("isRequisitioner", typeof(bool));
    
            var isBuyerParameter = isBuyer.HasValue ?
                new ObjectParameter("isBuyer", isBuyer) :
                new ObjectParameter("isBuyer", typeof(bool));
    
            var isAuthorizerParameter = isAuthorizer.HasValue ?
                new ObjectParameter("isAuthorizer", isAuthorizer) :
                new ObjectParameter("isAuthorizer", typeof(bool));
    
            var viewOnlyParameter = viewOnly.HasValue ?
                new ObjectParameter("ViewOnly", viewOnly) :
                new ObjectParameter("ViewOnly", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionList_Result>("sp_GetRequisitionList", companyParameter, usernameParameter, isAdminParameter, isRequisitionerParameter, isBuyerParameter, isAuthorizerParameter, viewOnlyParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionPoTotals_Result> sp_GetRequisitionPoTotals(string purchaseOrder)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionPoTotals_Result>("sp_GetRequisitionPoTotals", purchaseOrderParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionQuoteByLine_Result> sp_GetRequisitionQuoteByLine(string requisition, Nullable<int> line)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            var lineParameter = line.HasValue ?
                new ObjectParameter("Line", line) :
                new ObjectParameter("Line", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionQuoteByLine_Result>("sp_GetRequisitionQuoteByLine", requisitionParameter, lineParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionQuoteLines_Result> sp_GetRequisitionQuoteLines(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionQuoteLines_Result>("sp_GetRequisitionQuoteLines", requisitionParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionQuotesUpload_Result> sp_GetRequisitionQuotesUpload(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionQuotesUpload_Result>("sp_GetRequisitionQuotesUpload", requisitionParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionTotals_Result> sp_GetRequisitionTotals(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionTotals_Result>("sp_GetRequisitionTotals", requisitionParameter);
        }
    
        public virtual ObjectResult<sp_GetStockCodeByBranch_Result> sp_GetStockCodeByBranch(string branch, string stockCode)
        {
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStockCodeByBranch_Result>("sp_GetStockCodeByBranch", branchParameter, stockCodeParameter);
        }
    
        public virtual ObjectResult<sp_GetStockCodeByBranchSite_Result> sp_GetStockCodeByBranchSite(string branch, string site, string stockCode)
        {
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStockCodeByBranchSite_Result>("sp_GetStockCodeByBranchSite", branchParameter, siteParameter, stockCodeParameter);
        }
    
        public virtual ObjectResult<sp_GetSupplierByRequisitionAndLine_Result> sp_GetSupplierByRequisitionAndLine(string requisition, Nullable<int> line)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            var lineParameter = line.HasValue ?
                new ObjectParameter("Line", line) :
                new ObjectParameter("Line", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSupplierByRequisitionAndLine_Result>("sp_GetSupplierByRequisitionAndLine", requisitionParameter, lineParameter);
        }
    
        public virtual ObjectResult<sp_GetSupplierInvoiceValidation_Result> sp_GetSupplierInvoiceValidation(string supplier, string invoice, string grn)
        {
            var supplierParameter = supplier != null ?
                new ObjectParameter("Supplier", supplier) :
                new ObjectParameter("Supplier", typeof(string));
    
            var invoiceParameter = invoice != null ?
                new ObjectParameter("Invoice", invoice) :
                new ObjectParameter("Invoice", typeof(string));
    
            var grnParameter = grn != null ?
                new ObjectParameter("Grn", grn) :
                new ObjectParameter("Grn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSupplierInvoiceValidation_Result>("sp_GetSupplierInvoiceValidation", supplierParameter, invoiceParameter, grnParameter);
        }
    
        public virtual ObjectResult<sp_GetSuppliersForPo_Result> sp_GetSuppliersForPo(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSuppliersForPo_Result>("sp_GetSuppliersForPo", requisitionParameter);
        }
    
        public virtual ObjectResult<sp_GetSuppliersForQuoting_Result> sp_GetSuppliersForQuoting(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSuppliersForQuoting_Result>("sp_GetSuppliersForQuoting", requisitionParameter);
        }
    
        public virtual ObjectResult<sp_GetSysproProductClass_Result> sp_GetSysproProductClass(string filterText)
        {
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSysproProductClass_Result>("sp_GetSysproProductClass", filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetSysproSuppliers_Result> sp_GetSysproSuppliers(string filterText)
        {
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSysproSuppliers_Result>("sp_GetSysproSuppliers", filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetSysproWarehouses_Result> sp_GetSysproWarehouses(string filterText)
        {
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSysproWarehouses_Result>("sp_GetSysproWarehouses", filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetWarehouseByStockCode_Result> sp_GetWarehouseByStockCode(string stockCode)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetWarehouseByStockCode_Result>("sp_GetWarehouseByStockCode", stockCodeParameter);
        }
    
        public virtual ObjectResult<sp_PurchaseOrderGrnList_Result> sp_PurchaseOrderGrnList(string company, string username)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PurchaseOrderGrnList_Result>("sp_PurchaseOrderGrnList", companyParameter, usernameParameter);
        }
    
        public virtual ObjectResult<sp_PurchaseOrderList_Result> sp_PurchaseOrderList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PurchaseOrderList_Result>("sp_PurchaseOrderList");
        }
    
        public virtual int sp_SavePoAnalysisCategory(string purchaseOrder)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SavePoAnalysisCategory", purchaseOrderParameter);
        }
    
        public virtual int sp_UpdatePoLineInReq(string purchaseOrder)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdatePoLineInReq", purchaseOrderParameter);
        }
    
        public virtual int f_GenTransStkDesc(string company, Nullable<int> glYear, Nullable<int> glPeriod, Nullable<int> journal, string trnSource)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var glYearParameter = glYear.HasValue ?
                new ObjectParameter("GlYear", glYear) :
                new ObjectParameter("GlYear", typeof(int));
    
            var glPeriodParameter = glPeriod.HasValue ?
                new ObjectParameter("GlPeriod", glPeriod) :
                new ObjectParameter("GlPeriod", typeof(int));
    
            var journalParameter = journal.HasValue ?
                new ObjectParameter("Journal", journal) :
                new ObjectParameter("Journal", typeof(int));
    
            var trnSourceParameter = trnSource != null ?
                new ObjectParameter("TrnSource", trnSource) :
                new ObjectParameter("TrnSource", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_GenTransStkDesc", companyParameter, glYearParameter, glPeriodParameter, journalParameter, trnSourceParameter);
        }
    
        public virtual int sp_UpdateGrnForPosting()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateGrnForPosting");
        }
    
        public virtual int sp_SaveGlCodeAccess(string company, string username, string reportIndex2)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var reportIndex2Parameter = reportIndex2 != null ?
                new ObjectParameter("ReportIndex2", reportIndex2) :
                new ObjectParameter("ReportIndex2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SaveGlCodeAccess", companyParameter, usernameParameter, reportIndex2Parameter);
        }
    
        public virtual ObjectResult<sp_GetProvGlJournal_Result> sp_GetProvGlJournal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProvGlJournal_Result>("sp_GetProvGlJournal");
        }
    
        public virtual ObjectResult<sp_GetQuoteAnalysis_Result> sp_GetQuoteAnalysis(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetQuoteAnalysis_Result>("sp_GetQuoteAnalysis", requisitionParameter);
        }
    
        public virtual ObjectResult<sp_GetReqStatus_Result> sp_GetReqStatus(string company, string username, Nullable<bool> isRequisitioner, Nullable<bool> isBuyer, Nullable<bool> isAuthorizer, Nullable<bool> isAdmin, Nullable<bool> isError)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var isRequisitionerParameter = isRequisitioner.HasValue ?
                new ObjectParameter("isRequisitioner", isRequisitioner) :
                new ObjectParameter("isRequisitioner", typeof(bool));
    
            var isBuyerParameter = isBuyer.HasValue ?
                new ObjectParameter("isBuyer", isBuyer) :
                new ObjectParameter("isBuyer", typeof(bool));
    
            var isAuthorizerParameter = isAuthorizer.HasValue ?
                new ObjectParameter("isAuthorizer", isAuthorizer) :
                new ObjectParameter("isAuthorizer", typeof(bool));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("isAdmin", isAdmin) :
                new ObjectParameter("isAdmin", typeof(bool));
    
            var isErrorParameter = isError.HasValue ?
                new ObjectParameter("isError", isError) :
                new ObjectParameter("isError", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetReqStatus_Result>("sp_GetReqStatus", companyParameter, usernameParameter, isRequisitionerParameter, isBuyerParameter, isAuthorizerParameter, isAdminParameter, isErrorParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionAudit_Result> sp_GetRequisitionAudit(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string filterText, string filterText2)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            var filterText2Parameter = filterText2 != null ?
                new ObjectParameter("FilterText2", filterText2) :
                new ObjectParameter("FilterText2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionAudit_Result>("sp_GetRequisitionAudit", fromDateParameter, toDateParameter, filterTextParameter, filterText2Parameter);
        }
    
        public virtual ObjectResult<sp_GetStockCodePurchaseHistory_Result> sp_GetStockCodePurchaseHistory(string stockCode, string filterText)
        {
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStockCodePurchaseHistory_Result>("sp_GetStockCodePurchaseHistory", stockCodeParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetSupplierPurchaseHistory_Result> sp_GetSupplierPurchaseHistory(string supplier, string filterText)
        {
            var supplierParameter = supplier != null ?
                new ObjectParameter("Supplier", supplier) :
                new ObjectParameter("Supplier", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSupplierPurchaseHistory_Result>("sp_GetSupplierPurchaseHistory", supplierParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetBuyerStatsBranchList_Result> sp_GetBuyerStatsBranchList(string username, string company)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBuyerStatsBranchList_Result>("sp_GetBuyerStatsBranchList", usernameParameter, companyParameter);
        }
    
        public virtual ObjectResult<sp_GetBuyerStatsBuyerList_Result> sp_GetBuyerStatsBuyerList(string username, string company)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBuyerStatsBuyerList_Result>("sp_GetBuyerStatsBuyerList", usernameParameter, companyParameter);
        }
    
        public virtual ObjectResult<sp_GetPurchaseOrderEnquiryList_Result> sp_GetPurchaseOrderEnquiryList(string username, string company, string filterText)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPurchaseOrderEnquiryList_Result>("sp_GetPurchaseOrderEnquiryList", usernameParameter, companyParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetContractPrice_Result> sp_GetContractPrice(string branch, string site, string stockCode)
        {
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            var stockCodeParameter = stockCode != null ?
                new ObjectParameter("StockCode", stockCode) :
                new ObjectParameter("StockCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetContractPrice_Result>("sp_GetContractPrice", branchParameter, siteParameter, stockCodeParameter);
        }
    
        public virtual ObjectResult<sp_GetLastThreePurchases_Result> sp_GetLastThreePurchases(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetLastThreePurchases_Result>("sp_GetLastThreePurchases", requisitionParameter);
        }
    
        public virtual int sp_UpdatePoLineInGrn(string purchaseOrder)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdatePoLineInGrn", purchaseOrderParameter);
        }
    
        public virtual ObjectResult<sp_GetBuyerStats_Result> sp_GetBuyerStats(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<System.Guid> filterGuid)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var filterGuidParameter = filterGuid.HasValue ?
                new ObjectParameter("FilterGuid", filterGuid) :
                new ObjectParameter("FilterGuid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBuyerStats_Result>("sp_GetBuyerStats", startDateParameter, endDateParameter, filterGuidParameter);
        }
    
        public virtual ObjectResult<sp_GetBuyerStatsDetail_Result> sp_GetBuyerStatsDetail(Nullable<System.Guid> filterGuid, string detailType)
        {
            var filterGuidParameter = filterGuid.HasValue ?
                new ObjectParameter("FilterGuid", filterGuid) :
                new ObjectParameter("FilterGuid", typeof(System.Guid));
    
            var detailTypeParameter = detailType != null ?
                new ObjectParameter("DetailType", detailType) :
                new ObjectParameter("DetailType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBuyerStatsDetail_Result>("sp_GetBuyerStatsDetail", filterGuidParameter, detailTypeParameter);
        }
    
        public virtual ObjectResult<sp_GetPriceForPoLine_Result> sp_GetPriceForPoLine(string purchaseOrder, Nullable<int> line, string newGlCode, string newStockCode, Nullable<System.DateTime> invoiceDate)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            var lineParameter = line.HasValue ?
                new ObjectParameter("Line", line) :
                new ObjectParameter("Line", typeof(int));
    
            var newGlCodeParameter = newGlCode != null ?
                new ObjectParameter("NewGlCode", newGlCode) :
                new ObjectParameter("NewGlCode", typeof(string));
    
            var newStockCodeParameter = newStockCode != null ?
                new ObjectParameter("NewStockCode", newStockCode) :
                new ObjectParameter("NewStockCode", typeof(string));
    
            var invoiceDateParameter = invoiceDate.HasValue ?
                new ObjectParameter("InvoiceDate", invoiceDate) :
                new ObjectParameter("InvoiceDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPriceForPoLine_Result>("sp_GetPriceForPoLine", purchaseOrderParameter, lineParameter, newGlCodeParameter, newStockCodeParameter, invoiceDateParameter);
        }
    
        public virtual ObjectResult<sp_GetPurchaseOrderToCancel_Result> sp_GetPurchaseOrderToCancel(string purchaseOrder)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPurchaseOrderToCancel_Result>("sp_GetPurchaseOrderToCancel", purchaseOrderParameter);
        }
    
        public virtual ObjectResult<sp_GetUnpostedTransactionsCount_Result> sp_GetUnpostedTransactionsCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUnpostedTransactionsCount_Result>("sp_GetUnpostedTransactionsCount");
        }
    
        public virtual int sp_UpdateInvoiceAuthorisation(Nullable<int> authLevel, string grn, string username, Nullable<bool> authorised)
        {
            var authLevelParameter = authLevel.HasValue ?
                new ObjectParameter("AuthLevel", authLevel) :
                new ObjectParameter("AuthLevel", typeof(int));
    
            var grnParameter = grn != null ?
                new ObjectParameter("Grn", grn) :
                new ObjectParameter("Grn", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var authorisedParameter = authorised.HasValue ?
                new ObjectParameter("Authorised", authorised) :
                new ObjectParameter("Authorised", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateInvoiceAuthorisation", authLevelParameter, grnParameter, usernameParameter, authorisedParameter);
        }
    
        public virtual int sp_UpdateStockedWhCtlGlAcc(string purchaseOrder)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateStockedWhCtlGlAcc", purchaseOrderParameter);
        }
    
        public virtual int sp_UpdatePoDLinkJob(string purchaseOrder, Nullable<int> line)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            var lineParameter = line.HasValue ?
                new ObjectParameter("Line", line) :
                new ObjectParameter("Line", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdatePoDLinkJob", purchaseOrderParameter, lineParameter);
        }
    
        public virtual ObjectResult<sp_GetPeriodControl_Result> sp_GetPeriodControl(Nullable<decimal> finYear)
        {
            var finYearParameter = finYear.HasValue ?
                new ObjectParameter("FinYear", finYear) :
                new ObjectParameter("FinYear", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPeriodControl_Result>("sp_GetPeriodControl", finYearParameter);
        }
    
        public virtual ObjectResult<sp_GetStockCodeByBranchSiteFiltered_Result> sp_GetStockCodeByBranchSiteFiltered(string branch, string site, string search1, string search2, string search3, string search4, string search5)
        {
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var siteParameter = site != null ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(string));
    
            var search1Parameter = search1 != null ?
                new ObjectParameter("Search1", search1) :
                new ObjectParameter("Search1", typeof(string));
    
            var search2Parameter = search2 != null ?
                new ObjectParameter("Search2", search2) :
                new ObjectParameter("Search2", typeof(string));
    
            var search3Parameter = search3 != null ?
                new ObjectParameter("Search3", search3) :
                new ObjectParameter("Search3", typeof(string));
    
            var search4Parameter = search4 != null ?
                new ObjectParameter("Search4", search4) :
                new ObjectParameter("Search4", typeof(string));
    
            var search5Parameter = search5 != null ?
                new ObjectParameter("Search5", search5) :
                new ObjectParameter("Search5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStockCodeByBranchSiteFiltered_Result>("sp_GetStockCodeByBranchSiteFiltered", branchParameter, siteParameter, search1Parameter, search2Parameter, search3Parameter, search4Parameter, search5Parameter);
        }
    
        public virtual ObjectResult<sp_BuyerReqReport_Result> sp_BuyerReqReport(Nullable<System.Guid> filterGuid, string rptIndex)
        {
            var filterGuidParameter = filterGuid.HasValue ?
                new ObjectParameter("FilterGuid", filterGuid) :
                new ObjectParameter("FilterGuid", typeof(System.Guid));
    
            var rptIndexParameter = rptIndex != null ?
                new ObjectParameter("RptIndex", rptIndex) :
                new ObjectParameter("RptIndex", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuyerReqReport_Result>("sp_BuyerReqReport", filterGuidParameter, rptIndexParameter);
        }
    
        public virtual ObjectResult<sp_BuyerOutstandingPo_Result> sp_BuyerOutstandingPo(Nullable<System.Guid> filterGuid, string rptIndex)
        {
            var filterGuidParameter = filterGuid.HasValue ?
                new ObjectParameter("FilterGuid", filterGuid) :
                new ObjectParameter("FilterGuid", typeof(System.Guid));
    
            var rptIndexParameter = rptIndex != null ?
                new ObjectParameter("RptIndex", rptIndex) :
                new ObjectParameter("RptIndex", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuyerOutstandingPo_Result>("sp_BuyerOutstandingPo", filterGuidParameter, rptIndexParameter);
        }
    
        public virtual ObjectResult<sp_BuyerTurnaroundTimes_Result> sp_BuyerTurnaroundTimes(Nullable<System.Guid> filterGuid)
        {
            var filterGuidParameter = filterGuid.HasValue ?
                new ObjectParameter("FilterGuid", filterGuid) :
                new ObjectParameter("FilterGuid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuyerTurnaroundTimes_Result>("sp_BuyerTurnaroundTimes", filterGuidParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionStatusGrnList_Result> sp_GetRequisitionStatusGrnList(string company, string username, string filterText)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionStatusGrnList_Result>("sp_GetRequisitionStatusGrnList", companyParameter, usernameParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionStatusInvoiceList_Result> sp_GetRequisitionStatusInvoiceList(string company, string username, string filterText)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionStatusInvoiceList_Result>("sp_GetRequisitionStatusInvoiceList", companyParameter, usernameParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionStatusReqList_Result> sp_GetRequisitionStatusReqList(string company, string username, Nullable<bool> isAdmin, Nullable<bool> isRequisitioner, Nullable<bool> isBuyer, Nullable<bool> isAuthorizer, Nullable<bool> viewOnly, string filterText)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("isAdmin", isAdmin) :
                new ObjectParameter("isAdmin", typeof(bool));
    
            var isRequisitionerParameter = isRequisitioner.HasValue ?
                new ObjectParameter("isRequisitioner", isRequisitioner) :
                new ObjectParameter("isRequisitioner", typeof(bool));
    
            var isBuyerParameter = isBuyer.HasValue ?
                new ObjectParameter("isBuyer", isBuyer) :
                new ObjectParameter("isBuyer", typeof(bool));
    
            var isAuthorizerParameter = isAuthorizer.HasValue ?
                new ObjectParameter("isAuthorizer", isAuthorizer) :
                new ObjectParameter("isAuthorizer", typeof(bool));
    
            var viewOnlyParameter = viewOnly.HasValue ?
                new ObjectParameter("ViewOnly", viewOnly) :
                new ObjectParameter("ViewOnly", typeof(bool));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionStatusReqList_Result>("sp_GetRequisitionStatusReqList", companyParameter, usernameParameter, isAdminParameter, isRequisitionerParameter, isBuyerParameter, isAuthorizerParameter, viewOnlyParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetAllStockCodesFiltered_Result> sp_GetAllStockCodesFiltered(string search1, string search2, string search3, string search4, string search5)
        {
            var search1Parameter = search1 != null ?
                new ObjectParameter("Search1", search1) :
                new ObjectParameter("Search1", typeof(string));
    
            var search2Parameter = search2 != null ?
                new ObjectParameter("Search2", search2) :
                new ObjectParameter("Search2", typeof(string));
    
            var search3Parameter = search3 != null ?
                new ObjectParameter("Search3", search3) :
                new ObjectParameter("Search3", typeof(string));
    
            var search4Parameter = search4 != null ?
                new ObjectParameter("Search4", search4) :
                new ObjectParameter("Search4", typeof(string));
    
            var search5Parameter = search5 != null ?
                new ObjectParameter("Search5", search5) :
                new ObjectParameter("Search5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllStockCodesFiltered_Result>("sp_GetAllStockCodesFiltered", search1Parameter, search2Parameter, search3Parameter, search4Parameter, search5Parameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionStatusGrnListByGL_Result> sp_GetRequisitionStatusGrnListByGL(string company, string username, string glCode, string job)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var glCodeParameter = glCode != null ?
                new ObjectParameter("GlCode", glCode) :
                new ObjectParameter("GlCode", typeof(string));
    
            var jobParameter = job != null ?
                new ObjectParameter("Job", job) :
                new ObjectParameter("Job", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionStatusGrnListByGL_Result>("sp_GetRequisitionStatusGrnListByGL", companyParameter, usernameParameter, glCodeParameter, jobParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionStatusInvoiceListByGL_Result> sp_GetRequisitionStatusInvoiceListByGL(string company, string username, string glCode, string job)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var glCodeParameter = glCode != null ?
                new ObjectParameter("GlCode", glCode) :
                new ObjectParameter("GlCode", typeof(string));
    
            var jobParameter = job != null ?
                new ObjectParameter("Job", job) :
                new ObjectParameter("Job", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionStatusInvoiceListByGL_Result>("sp_GetRequisitionStatusInvoiceListByGL", companyParameter, usernameParameter, glCodeParameter, jobParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionStatusReqListByGL_Result> sp_GetRequisitionStatusReqListByGL(string company, string username, Nullable<bool> isAdmin, Nullable<bool> isRequisitioner, Nullable<bool> isBuyer, Nullable<bool> isAuthorizer, Nullable<bool> viewOnly, string glCode, string job)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("isAdmin", isAdmin) :
                new ObjectParameter("isAdmin", typeof(bool));
    
            var isRequisitionerParameter = isRequisitioner.HasValue ?
                new ObjectParameter("isRequisitioner", isRequisitioner) :
                new ObjectParameter("isRequisitioner", typeof(bool));
    
            var isBuyerParameter = isBuyer.HasValue ?
                new ObjectParameter("isBuyer", isBuyer) :
                new ObjectParameter("isBuyer", typeof(bool));
    
            var isAuthorizerParameter = isAuthorizer.HasValue ?
                new ObjectParameter("isAuthorizer", isAuthorizer) :
                new ObjectParameter("isAuthorizer", typeof(bool));
    
            var viewOnlyParameter = viewOnly.HasValue ?
                new ObjectParameter("ViewOnly", viewOnly) :
                new ObjectParameter("ViewOnly", typeof(bool));
    
            var glCodeParameter = glCode != null ?
                new ObjectParameter("GlCode", glCode) :
                new ObjectParameter("GlCode", typeof(string));
    
            var jobParameter = job != null ?
                new ObjectParameter("Job", job) :
                new ObjectParameter("Job", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionStatusReqListByGL_Result>("sp_GetRequisitionStatusReqListByGL", companyParameter, usernameParameter, isAdminParameter, isRequisitionerParameter, isBuyerParameter, isAuthorizerParameter, viewOnlyParameter, glCodeParameter, jobParameter);
        }
    
        public virtual ObjectResult<sp_GetGlCodesByUser_Result> sp_GetGlCodesByUser(string username, string company, string filterText)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGlCodesByUser_Result>("sp_GetGlCodesByUser", usernameParameter, companyParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetInvoiceReviewTotals_Result> sp_GetInvoiceReviewTotals()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetInvoiceReviewTotals_Result>("sp_GetInvoiceReviewTotals");
        }
    
        public virtual ObjectResult<sp_GetPeriodControlSetup_Result> sp_GetPeriodControlSetup(Nullable<int> finYear)
        {
            var finYearParameter = finYear.HasValue ?
                new ObjectParameter("FinYear", finYear) :
                new ObjectParameter("FinYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPeriodControlSetup_Result>("sp_GetPeriodControlSetup", finYearParameter);
        }
    
        public virtual int sp_DeletePeriodByYear(Nullable<int> finYear)
        {
            var finYearParameter = finYear.HasValue ?
                new ObjectParameter("FinYear", finYear) :
                new ObjectParameter("FinYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeletePeriodByYear", finYearParameter);
        }
    
        public virtual int sp_SavePeriodControl(Nullable<int> finYear, Nullable<int> finMonth, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var finYearParameter = finYear.HasValue ?
                new ObjectParameter("FinYear", finYear) :
                new ObjectParameter("FinYear", typeof(int));
    
            var finMonthParameter = finMonth.HasValue ?
                new ObjectParameter("FinMonth", finMonth) :
                new ObjectParameter("FinMonth", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SavePeriodControl", finYearParameter, finMonthParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int sp_SaveCurrentPeriod(Nullable<int> finYear, Nullable<int> finMonth)
        {
            var finYearParameter = finYear.HasValue ?
                new ObjectParameter("FinYear", finYear) :
                new ObjectParameter("FinYear", typeof(int));
    
            var finMonthParameter = finMonth.HasValue ?
                new ObjectParameter("FinMonth", finMonth) :
                new ObjectParameter("FinMonth", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SaveCurrentPeriod", finYearParameter, finMonthParameter);
        }
    
        public virtual ObjectResult<sp_BuyerTurnaroundTimesDetail_Result> sp_BuyerTurnaroundTimesDetail(Nullable<System.Guid> filterGuid, string report)
        {
            var filterGuidParameter = filterGuid.HasValue ?
                new ObjectParameter("FilterGuid", filterGuid) :
                new ObjectParameter("FilterGuid", typeof(System.Guid));
    
            var reportParameter = report != null ?
                new ObjectParameter("Report", report) :
                new ObjectParameter("Report", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuyerTurnaroundTimesDetail_Result>("sp_BuyerTurnaroundTimesDetail", filterGuidParameter, reportParameter);
        }
    
        public virtual ObjectResult<sp_GetJobList_Result> sp_GetJobList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetJobList_Result>("sp_GetJobList");
        }
    
        public virtual ObjectResult<sp_GetGlCodeTagList_Result> sp_GetGlCodeTagList(string username, string company, string filterText)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGlCodeTagList_Result>("sp_GetGlCodeTagList", usernameParameter, companyParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetGlCodeTagDetail_Result> sp_GetGlCodeTagDetail(string glCode, string analysisCode)
        {
            var glCodeParameter = glCode != null ?
                new ObjectParameter("GlCode", glCode) :
                new ObjectParameter("GlCode", typeof(string));
    
            var analysisCodeParameter = analysisCode != null ?
                new ObjectParameter("AnalysisCode", analysisCode) :
                new ObjectParameter("AnalysisCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetGlCodeTagDetail_Result>("sp_GetGlCodeTagDetail", glCodeParameter, analysisCodeParameter);
        }
    
        public virtual ObjectResult<sp_GetAuditTrail_Result> sp_GetAuditTrail(string filterText)
        {
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAuditTrail_Result>("sp_GetAuditTrail", filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetSupplierPurchaseHistoryHeader_Result> sp_GetSupplierPurchaseHistoryHeader(string supplier, string filterText)
        {
            var supplierParameter = supplier != null ?
                new ObjectParameter("Supplier", supplier) :
                new ObjectParameter("Supplier", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSupplierPurchaseHistoryHeader_Result>("sp_GetSupplierPurchaseHistoryHeader", supplierParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetSupplierPurchaseHistoryDetail_Result> sp_GetSupplierPurchaseHistoryDetail(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSupplierPurchaseHistoryDetail_Result>("sp_GetSupplierPurchaseHistoryDetail", requisitionParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionStatusPostedInvoiceList_Result> sp_GetRequisitionStatusPostedInvoiceList(string company, string username, string filterText)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionStatusPostedInvoiceList_Result>("sp_GetRequisitionStatusPostedInvoiceList", companyParameter, usernameParameter, filterTextParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionStatusPostedInvoiceListByGL_Result> sp_GetRequisitionStatusPostedInvoiceListByGL(string company, string username, string glCode, string job)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var glCodeParameter = glCode != null ?
                new ObjectParameter("GlCode", glCode) :
                new ObjectParameter("GlCode", typeof(string));
    
            var jobParameter = job != null ?
                new ObjectParameter("Job", job) :
                new ObjectParameter("Job", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionStatusPostedInvoiceListByGL_Result>("sp_GetRequisitionStatusPostedInvoiceListByGL", companyParameter, usernameParameter, glCodeParameter, jobParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionStatusAwaitingAuthByGL_Result> sp_GetRequisitionStatusAwaitingAuthByGL(string company, string username, string glCode, string job)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var glCodeParameter = glCode != null ?
                new ObjectParameter("GlCode", glCode) :
                new ObjectParameter("GlCode", typeof(string));
    
            var jobParameter = job != null ?
                new ObjectParameter("Job", job) :
                new ObjectParameter("Job", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionStatusAwaitingAuthByGL_Result>("sp_GetRequisitionStatusAwaitingAuthByGL", companyParameter, usernameParameter, glCodeParameter, jobParameter);
        }
    
        public virtual ObjectResult<sp_GetRequisitionStatusAwaitingAuthList_Result> sp_GetRequisitionStatusAwaitingAuthList(string company, string username, string filterText)
        {
            var companyParameter = company != null ?
                new ObjectParameter("Company", company) :
                new ObjectParameter("Company", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetRequisitionStatusAwaitingAuthList_Result>("sp_GetRequisitionStatusAwaitingAuthList", companyParameter, usernameParameter, filterTextParameter);
        }
    
        public virtual int sp_UpdateRequisitionLineDescription(string requisition, Nullable<int> line, string description)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            var lineParameter = line.HasValue ?
                new ObjectParameter("Line", line) :
                new ObjectParameter("Line", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateRequisitionLineDescription", requisitionParameter, lineParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<sp_GetBeeSuppliers_Result> sp_GetBeeSuppliers(string filterText)
        {
            var filterTextParameter = filterText != null ?
                new ObjectParameter("FilterText", filterText) :
                new ObjectParameter("FilterText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBeeSuppliers_Result>("sp_GetBeeSuppliers", filterTextParameter);
        }
    }
}
