//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblArTerm
    {
        public string TermsCode { get; set; }
        public string Description { get; set; }
        public decimal DiscPct { get; set; }
        public decimal DiscDays { get; set; }
        public decimal DueDays { get; set; }
        public string DiscountOption { get; set; }
        public string InvoiceOption { get; set; }
        public decimal DiscDayOfMonth { get; set; }
        public decimal DiscMonths { get; set; }
        public Nullable<System.DateTime> DiscDate { get; set; }
        public decimal InvDayOfMonth { get; set; }
        public decimal InvMonths { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public string AgeingCode { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
