//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCurrency
    {
        public TblCurrency()
        {
            this.ApSuppliers = new HashSet<ApSupplier>();
            this.PorMasterHdrs = new HashSet<PorMasterHdr>();
        }
    
        public string Currency { get; set; }
        public string Description { get; set; }
        public decimal BuyExchangeRate { get; set; }
        public string BuyMulDiv { get; set; }
        public decimal BuyEcDeclRate { get; set; }
        public string BuyEcDeclFact { get; set; }
        public decimal SellExchangeRate { get; set; }
        public string SellMulDiv { get; set; }
        public decimal SellEcDeclRate { get; set; }
        public string SellEcDeclFact { get; set; }
        public string TriangReqd { get; set; }
        public string IntermediateCur { get; set; }
        public string FixedRate { get; set; }
        public decimal Tolerance { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<ApSupplier> ApSuppliers { get; set; }
        public virtual ICollection<PorMasterHdr> PorMasterHdrs { get; set; }
    }
}
