//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJobMatData
    {
        public string Job { get; set; }
        public string StockCode { get; set; }
        public string Viscosity { get; set; }
        public string Reducer { get; set; }
        public string Retarder { get; set; }
    }
}
