//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJobSalesOrder
    {
        public string Job { get; set; }
        public string StockCode { get; set; }
        public string SalesOrder { get; set; }
        public decimal SalesOrderLine { get; set; }
        public string CustomerPoNumber { get; set; }
        public Nullable<System.DateTime> SystemOrderDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> HeaderShipDate { get; set; }
        public Nullable<System.DateTime> MLineShipDate { get; set; }
        public Nullable<System.DateTime> MCustRequestDat { get; set; }
        public decimal Width { get; set; }
        public decimal Length { get; set; }
        public decimal QtyAcross { get; set; }
        public decimal QtyAround { get; set; }
        public int CylinderCircu { get; set; }
        public Nullable<decimal> NumberUp { get; set; }
        public Nullable<decimal> YieldLm { get; set; }
        public string TemplateNumber { get; set; }
        public string DieRefNumber { get; set; }
        public string PrintingCode { get; set; }
        public string StockUom { get; set; }
        public decimal QtyToMake { get; set; }
        public string ProductClass { get; set; }
        public Nullable<decimal> PackQty { get; set; }
        public Nullable<decimal> NumOfPacks { get; set; }
    }
}
