//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSalesRegister
    {
        public decimal Register { get; set; }
        public string GlYear { get; set; }
        public string GlPeriod { get; set; }
        public string Company { get; set; }
        public string Branch { get; set; }
        public string BranchDesc { get; set; }
        public string Customer { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Document { get; set; }
        public string DocumentType { get; set; }
        public string Invoice { get; set; }
        public string StockCode { get; set; }
        public decimal NetSalesValue { get; set; }
        public decimal TaxValue { get; set; }
        public Nullable<decimal> Total { get; set; }
        public decimal QtyInvoiced { get; set; }
        public decimal CostValue { get; set; }
    }
}
