//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSorContPrice
    {
        public string ContractType { get; set; }
        public string CustomerBuyGrp { get; set; }
        public string StockCode { get; set; }
        public string Contract { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string PriceMethod { get; set; }
        public string FixedUom { get; set; }
        public string FixedPriceCode { get; set; }
        public decimal FixedPrice { get; set; }
        public decimal Discount1 { get; set; }
        public decimal Discount2 { get; set; }
        public decimal Discount3 { get; set; }
        public decimal CustListPrice { get; set; }
        public decimal QtyBreak { get; set; }
        public string QtyPrice { get; set; }
    }
}
