//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwWipJobMatSpec
    {
        public string SequenceNum { get; set; }
        public string Job { get; set; }
        public string StockCode { get; set; }
        public Nullable<int> AvgReelLength { get; set; }
        public Nullable<int> Gsm { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string CostCentre { get; set; }
    }
}
