//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megasoft2
{
    using System;
    using System.Collections.Generic;
    
    public partial class WipJobClass
    {
        public WipJobClass()
        {
            this.InvMasters = new HashSet<InvMaster>();
            this.WipMasters = new HashSet<WipMaster>();
        }
    
        public string JobClassification { get; set; }
        public string ClassDescription { get; set; }
        public string ClassJobPrefix { get; set; }
        public decimal ClassJobSuffix { get; set; }
        public string WipCtlGlCode { get; set; }
        public string WipInsGlCode { get; set; }
        public string WipAutoGlCode { get; set; }
        public string WipVarGlCode { get; set; }
        public string WipInspectPrefix { get; set; }
        public decimal NextInspReference { get; set; }
        public byte[] TimeStamp { get; set; }
        public string WipBranch { get; set; }
    
        public virtual ICollection<InvMaster> InvMasters { get; set; }
        public virtual ICollection<WipMaster> WipMasters { get; set; }
    }
}
