//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegasoftService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenMaster
    {
        public string Company { get; set; }
        public string GlCode { get; set; }
        public string Description { get; set; }
        public decimal NextGlLine { get; set; }
        public decimal NextGlLinePyr { get; set; }
        public string NextLine { get; set; }
        public string NextLinePyr { get; set; }
        public string ReportIndex1 { get; set; }
        public string ReportIndex2 { get; set; }
        public string AccountType { get; set; }
        public string ExpenseType { get; set; }
        public decimal PtdDrValue { get; set; }
        public decimal PtdCrValue { get; set; }
        public decimal CurrentBalance { get; set; }
        public decimal PrevPerEndBal { get; set; }
        public string GlGroup { get; set; }
        public string BudgetMethod { get; set; }
        public string ControlAccFlag { get; set; }
        public string AccOnHldFlag { get; set; }
        public string TaxCode { get; set; }
        public decimal NumDetailCurYr { get; set; }
        public decimal NumDetailPrvYr { get; set; }
        public string IntegrationMethod { get; set; }
        public string AltDescription { get; set; }
        public decimal Historical { get; set; }
        public string Tax2Code { get; set; }
        public string RevalCategory { get; set; }
        public string AltCurIndicator { get; set; }
        public string GlUnitOfMeasure { get; set; }
        public string BusinessProcess1 { get; set; }
        public string BusinessProcess2 { get; set; }
        public string BusinessProcess3 { get; set; }
        public string BusinessProcess4 { get; set; }
        public string BusinessProcess5 { get; set; }
        public string BusinessProcess6 { get; set; }
        public string BusinessProcess7 { get; set; }
        public string BusinessProcess8 { get; set; }
        public string BusinessProcess9 { get; set; }
        public string BusinessProcess10 { get; set; }
        public string AnalysisRequired { get; set; }
        public string AnalysisCategory { get; set; }
        public string CurrentInd { get; set; }
        public string RetEarnsAccount { get; set; }
        public string TaxAccount { get; set; }
        public string InterestAccount { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual AdmTax AdmTax { get; set; }
    }
}
