//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegasoftService
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtBranchSite
    {
        public string Branch { get; set; }
        public string Site { get; set; }
        public string SiteName { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string PhysicalAddress1 { get; set; }
        public string PhysicalAddress2 { get; set; }
        public string PhysicalAddress3 { get; set; }
        public string PhysicalAddress4 { get; set; }
        public string PhysicalAddress5 { get; set; }
        public string PostalAddress1 { get; set; }
        public string PostalAddress2 { get; set; }
        public string PostalAddress3 { get; set; }
        public string PostalAddress4 { get; set; }
        public string PostalAddress5 { get; set; }
        public string AccrualSuspenseAcc { get; set; }
        public string ApBranch { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> TrnDate { get; set; }
    }
}
