//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegasoftService
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtRequisitionSetting
    {
        public int SettingId { get; set; }
        public Nullable<decimal> OneQuoteMinValue { get; set; }
        public Nullable<decimal> OneQuoteMaxValue { get; set; }
        public Nullable<decimal> TwoQuoteMinValue { get; set; }
        public Nullable<decimal> TwoQuoteMaxValue { get; set; }
        public Nullable<decimal> ThreeQuoteMinValue { get; set; }
        public string RequestForQuoteOutputPath { get; set; }
        public Nullable<decimal> InvoiceReviewLimit { get; set; }
        public string ExemptTaxCode { get; set; }
        public string LastGrn { get; set; }
        public string NonStockedControlAccount { get; set; }
        public string GrnClearingAccount { get; set; }
    }
}
