//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegasoftService
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtRequisitionHeader
    {
        public string Requisition { get; set; }
        public Nullable<System.DateTime> RequisitionDate { get; set; }
        public string Requisitioner { get; set; }
        public string Branch { get; set; }
        public string Site { get; set; }
        public string Buyer { get; set; }
        public string Supplier { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string FromAddress1 { get; set; }
        public string FromAddress2 { get; set; }
        public string FromAddress3 { get; set; }
        public string FromAddress4 { get; set; }
        public string FromAddress5 { get; set; }
        public string ToAddress1 { get; set; }
        public string ToAddress2 { get; set; }
        public string ToAddress3 { get; set; }
        public string ToAddress4 { get; set; }
        public string ToAddress5 { get; set; }
        public bool Emergency { get; set; }
        public string EmergencyCode { get; set; }
        public string EmergencyReason { get; set; }
        public bool Completed { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public bool Accepted { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public bool QuoteReceived { get; set; }
        public Nullable<System.DateTime> QuoteReceivedDate { get; set; }
        public bool QuoteOverride { get; set; }
        public string QuoteOverrideReasonCode { get; set; }
        public string QuoteOverrideReason { get; set; }
        public bool Authorised { get; set; }
        public Nullable<System.DateTime> AuthorisedDate { get; set; }
        public string AuthorisedBy { get; set; }
        public bool Query { get; set; }
        public string JobDescription { get; set; }
        public string SpecialInstructions { get; set; }
        public string ItemsDescription { get; set; }
        public string PreferredSupplier1 { get; set; }
        public string PreferredSupplier2 { get; set; }
        public string PreferredSupplier3 { get; set; }
        public string PurchaseOrder { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Holder { get; set; }
        public string Currency { get; set; }
    }
}
