//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegasoftService
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtTmpPoToCancel
    {
        public string Requisition { get; set; }
        public string PurchaseOrder { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
