//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegasoftService
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtUser
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string SysproUsername { get; set; }
        public string SysproPassword { get; set; }
        public string DefaultPrinter { get; set; }
        public string DefaultApplication { get; set; }
        public string ReqPrefix { get; set; }
        public Nullable<int> LastReqNo { get; set; }
        public bool Administrator { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<decimal> AuthorizationLimit { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public bool BranchManager { get; set; }
        public bool ForcePasswordReset { get; set; }
        public bool IsBuyer { get; set; }
        public bool IsRequisitioner { get; set; }
    }
}
