//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegasoftService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorMasterDetail
    {
        public string PurchaseOrder { get; set; }
        public decimal Line { get; set; }
        public string LineType { get; set; }
        public string MStockCode { get; set; }
        public string MStockDes { get; set; }
        public string MWarehouse { get; set; }
        public string MOrderUom { get; set; }
        public string MStockingUom { get; set; }
        public decimal MOrderQty { get; set; }
        public decimal MReceivedQty { get; set; }
        public Nullable<System.DateTime> MLatestDueDate { get; set; }
        public Nullable<System.DateTime> MLastReceiptDat { get; set; }
        public string MSupCatalogue { get; set; }
        public decimal MDiscPct1 { get; set; }
        public decimal MDiscPct2 { get; set; }
        public decimal MDiscPct3 { get; set; }
        public string MDiscValFlag { get; set; }
        public decimal MDiscValue { get; set; }
        public decimal MPrice { get; set; }
        public decimal MForeignPrice { get; set; }
        public decimal MDecimalsToPrt { get; set; }
        public decimal MConvFactPrcUm { get; set; }
        public string MMulDivPrc { get; set; }
        public string MPriceUom { get; set; }
        public string MTaxCode { get; set; }
        public decimal MConvFactOrdUm { get; set; }
        public string MMulDivAlloc { get; set; }
        public string MProductClass { get; set; }
        public string MCompleteFlag { get; set; }
        public string MJob { get; set; }
        public string MJobLine { get; set; }
        public string MGlCode { get; set; }
        public string MUserAuthReqn { get; set; }
        public string MRequisition { get; set; }
        public decimal MRequisitionLine { get; set; }
        public string MSalesOrder { get; set; }
        public decimal MSalesOrderLine { get; set; }
        public Nullable<System.DateTime> MOrigDueDate { get; set; }
        public string MReschedDueDate { get; set; }
        public string MLctConfirmed { get; set; }
        public decimal MOriginalLine { get; set; }
        public decimal MSubcontractOp { get; set; }
        public string MEdiExtractFlag { get; set; }
        public string MEdiActionFlag { get; set; }
        public string MInspectionReqd { get; set; }
        public decimal MNonsUnitMass { get; set; }
        public decimal MNonsUnitVol { get; set; }
        public string MVersion { get; set; }
        public string MRelease { get; set; }
        public string NComment { get; set; }
        public decimal NCommentFromLin { get; set; }
        public decimal NMscChargeValue { get; set; }
        public string NMscChargePrint { get; set; }
        public string NComPrintType { get; set; }
        public string NMscChargeTax { get; set; }
        public string NCommentFlag { get; set; }
        public decimal NMscChargeFor { get; set; }
        public string NMscChargeFLoc { get; set; }
        public string NEdiExtract { get; set; }
        public string MEccFlag { get; set; }
        public Nullable<System.DateTime> MBlanketDate { get; set; }
        public string MContractNumber { get; set; }
        public decimal MBlanketContLine { get; set; }
        public string AssetFlag { get; set; }
        public string CapexCode { get; set; }
        public decimal CapexLine { get; set; }
        public string SelectionCode { get; set; }
        public string SelectionType { get; set; }
        public string User1 { get; set; }
        public string OrderLineStatus { get; set; }
        public string AutoVoucherReqd { get; set; }
        public string IncludeInMrp { get; set; }
        public string WithTaxExpenseType { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual AdmTax AdmTax { get; set; }
        public virtual WipMaster WipMaster { get; set; }
    }
}
