//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegasoftService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrjProjHier
    {
        public string Job { get; set; }
        public string HierHead { get; set; }
        public string Section1 { get; set; }
        public string Section2 { get; set; }
        public string Section3 { get; set; }
        public string Section4 { get; set; }
        public string TrnType { get; set; }
        public string PurchaseOrder { get; set; }
        public decimal PurchaseOrderLin { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string StockCode { get; set; }
        public string PostJob { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual WipMaster WipMaster { get; set; }
    }
}
