//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegasoftService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SysproEntities : DbContext
    {
        public SysproEntities()
            : base("name=SysproEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmTax> AdmTaxes { get; set; }
        public virtual DbSet<PorMasterDetail> PorMasterDetails { get; set; }
        public virtual DbSet<PrjProjHier> PrjProjHiers { get; set; }
        public virtual DbSet<WipJobAllMat> WipJobAllMats { get; set; }
        public virtual DbSet<WipMaster> WipMasters { get; set; }
        public virtual DbSet<mtBranchSite> mtBranchSites { get; set; }
        public virtual DbSet<mtRequisitionSetting> mtRequisitionSettings { get; set; }
        public virtual DbSet<ApSupplier> ApSuppliers { get; set; }
        public virtual DbSet<mtApSupplier> mtApSuppliers { get; set; }
        public virtual DbSet<mtRequisitionHeader> mtRequisitionHeaders { get; set; }
        public virtual DbSet<mtRequisitionTextLine> mtRequisitionTextLines { get; set; }
        public virtual DbSet<mtGrnDetail> mtGrnDetails { get; set; }
        public virtual DbSet<mtRequisitionDetail> mtRequisitionDetails { get; set; }
        public virtual DbSet<GenMaster> GenMasters { get; set; }
        public virtual DbSet<CusGenMaster_> CusGenMaster_ { get; set; }
        public virtual DbSet<mtTmpPoToCancel> mtTmpPoToCancels { get; set; }
    
        public virtual ObjectResult<sp_GetInvoiceDetailsByGrn_Result> sp_GetInvoiceDetailsByGrn(string grn)
        {
            var grnParameter = grn != null ?
                new ObjectParameter("Grn", grn) :
                new ObjectParameter("Grn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetInvoiceDetailsByGrn_Result>("sp_GetInvoiceDetailsByGrn", grnParameter);
        }
    
        public virtual ObjectResult<sp_GetPoLinesForMaterialAllocation_Result> sp_GetPoLinesForMaterialAllocation(string grn)
        {
            var grnParameter = grn != null ?
                new ObjectParameter("Grn", grn) :
                new ObjectParameter("Grn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPoLinesForMaterialAllocation_Result>("sp_GetPoLinesForMaterialAllocation", grnParameter);
        }
    
        public virtual int sp_UpdatePurchaseOrderReceiptQty(string grn)
        {
            var grnParameter = grn != null ?
                new ObjectParameter("Grn", grn) :
                new ObjectParameter("Grn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdatePurchaseOrderReceiptQty", grnParameter);
        }
    
        public virtual ObjectResult<sp_GetSuppliersForPo_Result> sp_GetSuppliersForPo(string requisition)
        {
            var requisitionParameter = requisition != null ?
                new ObjectParameter("Requisition", requisition) :
                new ObjectParameter("Requisition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSuppliersForPo_Result>("sp_GetSuppliersForPo", requisitionParameter);
        }
    
        public virtual int sp_UpdatePoLineInReq(string purchaseOrder)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdatePoLineInReq", purchaseOrderParameter);
        }
    
        public virtual int sp_SavePoAnalysisCategory(string purchaseOrder)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SavePoAnalysisCategory", purchaseOrderParameter);
        }
    
        public virtual ObjectResult<sp_GetAPPostingPeriod_Result> sp_GetAPPostingPeriod(Nullable<int> grnYear, Nullable<int> grnMonth)
        {
            var grnYearParameter = grnYear.HasValue ?
                new ObjectParameter("GrnYear", grnYear) :
                new ObjectParameter("GrnYear", typeof(int));
    
            var grnMonthParameter = grnMonth.HasValue ?
                new ObjectParameter("GrnMonth", grnMonth) :
                new ObjectParameter("GrnMonth", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAPPostingPeriod_Result>("sp_GetAPPostingPeriod", grnYearParameter, grnMonthParameter);
        }
    
        public virtual ObjectResult<sp_GetPurchaseOrderToCancel_Result> sp_GetPurchaseOrderToCancel(string purchaseOrder)
        {
            var purchaseOrderParameter = purchaseOrder != null ?
                new ObjectParameter("PurchaseOrder", purchaseOrder) :
                new ObjectParameter("PurchaseOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPurchaseOrderToCancel_Result>("sp_GetPurchaseOrderToCancel", purchaseOrderParameter);
        }
    }
}
